using System.Collections.Generic;

namespace CodeCave.Revit.Toolkit
{
    /// <summary>
    /// Extensions for Revit API BuiltInCategory enum
    /// </summary>
    public static class BuiltInCategoryExtensions
    {
        private static readonly Dictionary<BuiltInCategory, string> knownCategories;

        static BuiltInCategoryExtensions()
        {
            knownCategories = new Dictionary<BuiltInCategory, string>
            {
                { BuiltInCategory.OST_LinksAnalytical, "Analytical Links" },
                { BuiltInCategory.OST_FoundationSlabAnalyticalTags, "Analytical Slab Foundation Tags" },
                { BuiltInCategory.OST_WallFoundationAnalyticalTags, "Analytical Wall Foundation Tags" },
                { BuiltInCategory.OST_IsolatedFoundationAnalyticalTags, "Analytical Isolated Foundation Tags" },
                { BuiltInCategory.OST_WallAnalyticalTags, "Analytical Wall Tags" },
                { BuiltInCategory.OST_FloorAnalyticalTags, "Analytical Floor Tags" },
                { BuiltInCategory.OST_ColumnAnalyticalTags, "Analytical Column Tags" },
                { BuiltInCategory.OST_BraceAnalyticalTags, "Analytical Brace Tags" },
                { BuiltInCategory.OST_BeamAnalyticalTags, "Analytical Beam Tags" },
                { BuiltInCategory.OST_AnalyticalNodes, "Analytical Nodes" },
                { BuiltInCategory.OST_FoundationSlabAnalytical, "Analytical Foundation Slabs" },
                { BuiltInCategory.OST_WallFoundationAnalytical, "Analytical Wall Foundations" },
                { BuiltInCategory.OST_IsolatedFoundationAnalytical, "Analytical Isolated Foundations" },
                { BuiltInCategory.OST_WallAnalytical, "Analytical Walls" },
                { BuiltInCategory.OST_FloorAnalytical, "Analytical Floors" },
                { BuiltInCategory.OST_ColumnEndSegment, "Top Segment" },
                { BuiltInCategory.OST_ColumnStartSegment, "Base Segment" },
                { BuiltInCategory.OST_ColumnAnalytical, "Analytical Columns" },
                { BuiltInCategory.OST_BraceEndSegment, "End Segment" },
                { BuiltInCategory.OST_BraceStartSegment, "Start Segment" },
                { BuiltInCategory.OST_BraceAnalytical, "Analytical Braces" },
                { BuiltInCategory.OST_BeamEndSegment, "End Segment" },
                { BuiltInCategory.OST_BeamStartSegment, "Start Segment" },
                { BuiltInCategory.OST_BeamAnalytical, "Analytical Beams" },
                { BuiltInCategory.OST_StructuralTrussStickSymbols, "Stick Symbols" },
                { BuiltInCategory.OST_MassHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CurtaSystemHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_EntourageHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_PlantingHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_SpecialityEquipmentHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_TopographyHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_SiteHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_RoadsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ParkingHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_PlumbingFixturesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_MechanicalEquipmentHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_LightingFixturesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_FurnitureSystemsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ElectricalFixturesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ElectricalEquipmentHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CaseworkHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_DetailComponentsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ShaftOpeningHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_GenericModelHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CurtainWallMullionsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CurtainWallPanelsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_RampsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StairsRailingHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StairsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ColumnsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_FurnitureHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_LinesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CeilingsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_RoofsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_DoorsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_WindowsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CouplerHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CouplerTags, "Structural Rebar Coupler Tags" },
                { BuiltInCategory.OST_Coupler, "Structural Rebar Couplers" },
                { BuiltInCategory.OST_RebarHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructConnectionOthers, "Others" },
                { BuiltInCategory.OST_StructConnectionBolts, "Bolts" },
                { BuiltInCategory.OST_StructConnectionTags, "Structural Connection Tags" },
                { BuiltInCategory.OST_StructConnectionAnchors, "Anchors" },
                { BuiltInCategory.OST_StructConnectionPlates, "Plates" },
                { BuiltInCategory.OST_StructConnectionProfiles, "Profiles" },
                { BuiltInCategory.OST_StructConnectionReference, "Reference" },
                { BuiltInCategory.OST_StructConnectionSymbol, "Symbol" },
                { BuiltInCategory.OST_StructConnectionHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructConnections, "Structural Connections" },
                { BuiltInCategory.OST_FabricAreaBoundary, "Boundary" },
                { BuiltInCategory.OST_FabricReinSpanSymbol, "Structural Fabric Reinforcement Symbols" },
                { BuiltInCategory.OST_FabricReinforcementWire, "Fabric Wire" },
                { BuiltInCategory.OST_FabricReinforcementBoundary, "Boundary" },
                { BuiltInCategory.OST_RebarSetToggle, "Rebar Set Toggle" },
                { BuiltInCategory.OST_FabricReinforcementTags, "Structural Fabric Reinforcement Tags" },
                { BuiltInCategory.OST_AreaReinTags, "Structural Area Reinforcement Tags" },
                { BuiltInCategory.OST_RebarTags, "Structural Rebar Tags" },
                { BuiltInCategory.OST_FabricAreaSketchSheetsLines, "<Fabric Sheets>" },
                { BuiltInCategory.OST_FabricAreaSketchEnvelopeLines, "<Fabric Envelope>" },
                { BuiltInCategory.OST_FabricAreas, "Structural Fabric Areas" },
                { BuiltInCategory.OST_FabricReinforcement, "Structural Fabric Reinforcement" },
                { BuiltInCategory.OST_RebarCover, "Rebar Cover References" },
                { BuiltInCategory.OST_RebarShape, "Rebar Shape" },
                { BuiltInCategory.OST_PathReinBoundary, "Boundary" },
                { BuiltInCategory.OST_PathReinTags, "Structural Path Reinforcement Tags" },
                { BuiltInCategory.OST_PathReinSpanSymbol, "Structural Path Reinforcement Symbols" },
                { BuiltInCategory.OST_PathRein, "Structural Path Reinforcement" },
                { BuiltInCategory.OST_AreaReinBoundary, "Boundary" },
                { BuiltInCategory.OST_AreaReinSpanSymbol, "Structural Area Reinforcement Symbols" },
                { BuiltInCategory.OST_AreaRein, "Structural Area Reinforcement" },
                { BuiltInCategory.OST_Rebar, "Structural Rebar" },
                { BuiltInCategory.OST_FabricationPipeworkInsulation, "Insulation" },
                { BuiltInCategory.OST_FabricationDuctworkLining, "Lining" },
                { BuiltInCategory.OST_FabricationContainmentDrop, "Drop" },
                { BuiltInCategory.OST_FabricationContainmentRise, "Rise" },
                { BuiltInCategory.OST_FabricationPipeworkDrop, "Drop" },
                { BuiltInCategory.OST_FabricationPipeworkRise, "Rise" },
                { BuiltInCategory.OST_FabricationContainmentSymbology, "Symbology" },
                { BuiltInCategory.OST_FabricationContainmentCenterLine, "Center Line" },
                { BuiltInCategory.OST_FabricationContainmentTags, "MEP Fabrication Containment Tags" },
                { BuiltInCategory.OST_FabricationContainment, "MEP Fabrication Containment" },
                { BuiltInCategory.OST_FabricationPipeworkSymbology, "Symbology" },
                { BuiltInCategory.OST_FabricationPipeworkCenterLine, "Center Line" },
                { BuiltInCategory.OST_FabricationPipeworkTags, "MEP Fabrication Pipework Tags" },
                { BuiltInCategory.OST_FabricationPipework, "MEP Fabrication Pipework" },
                { BuiltInCategory.OST_FabricationDuctworkSymbology, "Symbology" },
                { BuiltInCategory.OST_FabricationDuctworkDrop, "Drop" },
                { BuiltInCategory.OST_FabricationDuctworkRise, "Rise" },
                { BuiltInCategory.OST_FabricationHangerTags, "MEP Fabrication Hanger Tags" },
                { BuiltInCategory.OST_FabricationHangers, "MEP Fabrication Hangers" },
                { BuiltInCategory.OST_FabricationDuctworkInsulation, "Insulation" },
                { BuiltInCategory.OST_FabricationDuctworkCenterLine, "Center Line" },
                { BuiltInCategory.OST_FabricationDuctworkTags, "MEP Fabrication Ductwork Tags" },
                { BuiltInCategory.OST_FabricationDuctwork, "MEP Fabrication Ductwork" },
                { BuiltInCategory.OST_gbXML_Shade, "Shades" },
                { BuiltInCategory.OST_AnalyticSurfaces, "Analytical Surfaces" },
                { BuiltInCategory.OST_AnalyticSpaces, "Analytical Spaces" },
                { BuiltInCategory.OST_gbXML_OpeningAir, "Air Openings" },
                { BuiltInCategory.OST_gbXML_NonSlidingDoor, "Non-sliding Doors" },
                { BuiltInCategory.OST_gbXML_SlidingDoor, "Sliding Doors" },
                { BuiltInCategory.OST_gbXML_OperableSkylight, "Operable Skylights" },
                { BuiltInCategory.OST_gbXML_FixedSkylight, "Fixed Skylights" },
                { BuiltInCategory.OST_gbXML_OperableWindow, "Operable Windows" },
                { BuiltInCategory.OST_gbXML_FixedWindow, "Fixed Windows" },
                { BuiltInCategory.OST_gbXML_UndergroundCeiling, "Underground Ceilings" },
                { BuiltInCategory.OST_gbXML_UndergroundSlab, "Underground Slabs" },
                { BuiltInCategory.OST_gbXML_UndergroundWall, "Underground Walls" },
                { BuiltInCategory.OST_gbXML_SurfaceAir, "Air Surfaces" },
                { BuiltInCategory.OST_gbXML_Ceiling, "Ceilings" },
                { BuiltInCategory.OST_gbXML_InteriorFloor, "Interior Floors" },
                { BuiltInCategory.OST_gbXML_InteriorWall, "Interior Walls" },
                { BuiltInCategory.OST_gbXML_SlabOnGrade, "Slabs on Grade" },
                { BuiltInCategory.OST_gbXML_RaisedFloor, "Raised Floors" },
                { BuiltInCategory.OST_gbXML_Roof, "Roofs" },
                { BuiltInCategory.OST_gbXML_ExteriorWall, "Exterior Walls" },
                { BuiltInCategory.OST_PipeSegments, "Pipe Segments" },
                { BuiltInCategory.OST_PlaceHolderPipes, "Pipe Placeholders" },
                { BuiltInCategory.OST_PlaceHolderDucts, "Duct Placeholders" },
                { BuiltInCategory.OST_PipingSystem_Reference_Visibility, "Reference Lines" },
                { BuiltInCategory.OST_DuctSystem_Reference_Visibility, "Reference Lines" },
                { BuiltInCategory.OST_PipeInsulationsTags, "Pipe Insulation Tags" },
                { BuiltInCategory.OST_DuctLiningsTags, "Duct Lining Tags" },
                { BuiltInCategory.OST_DuctInsulationsTags, "Duct Insulation Tags" },
                { BuiltInCategory.OST_ElectricalInternalCircuits, "Electrical Spare/Space Circuits" },
                { BuiltInCategory.OST_PanelScheduleGraphics, "Panel Schedule Graphics" },
                { BuiltInCategory.OST_CableTrayRun, "Cable Tray Runs" },
                { BuiltInCategory.OST_ConduitRun, "Conduit Runs" },
                { BuiltInCategory.OST_ConduitFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_CableTrayFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_ConduitCenterLine, "Center line" },
                { BuiltInCategory.OST_ConduitDrop, "Drop" },
                { BuiltInCategory.OST_ConduitRiseDrop, "Rise" },
                { BuiltInCategory.OST_CableTrayCenterLine, "Center line" },
                { BuiltInCategory.OST_CableTrayDrop, "Drop" },
                { BuiltInCategory.OST_CableTrayRiseDrop, "Rise" },
                { BuiltInCategory.OST_ConduitTags, "Conduit Tags" },
                { BuiltInCategory.OST_Conduit, "Conduits" },
                { BuiltInCategory.OST_CableTrayTags, "Cable Tray Tags" },
                { BuiltInCategory.OST_CableTray, "Cable Trays" },
                { BuiltInCategory.OST_ConduitFittingTags, "Conduit Fitting Tags" },
                { BuiltInCategory.OST_ConduitFitting, "Conduit Fittings" },
                { BuiltInCategory.OST_CableTrayFittingTags, "Cable Tray Fitting Tags" },
                { BuiltInCategory.OST_CableTrayFitting, "Cable Tray Fittings" },
                { BuiltInCategory.OST_RoutingPreferences, "Routing Preferences" },
                { BuiltInCategory.OST_DuctLinings, "Duct Linings" },
                { BuiltInCategory.OST_DuctInsulations, "Duct Insulations" },
                { BuiltInCategory.OST_PipeInsulations, "Pipe Insulations" },
                { BuiltInCategory.OST_HVAC_Zones_Reference_Visibility, "Reference Lines" },
                { BuiltInCategory.OST_HVAC_Zones_InteriorFill_Visibility, "Interior Fill" },
                { BuiltInCategory.OST_HVAC_Zones_ColorFill, "Color Fill" },
                { BuiltInCategory.OST_ZoneTags, "Zone Tags" },
                { BuiltInCategory.OST_HVAC_Zones_Boundary, "Boundary" },
                { BuiltInCategory.OST_HVAC_Zones, "HVAC Zones" },
                { BuiltInCategory.OST_SwitchSystem, "Switch System" },
                { BuiltInCategory.OST_SprinklerTags, "Sprinkler Tags" },
                { BuiltInCategory.OST_Sprinklers, "Sprinklers" },
                { BuiltInCategory.OST_GbXML_Opening, "Opening" },
                { BuiltInCategory.OST_GbXML_SType_Underground, "Underground" },
                { BuiltInCategory.OST_GbXML_SType_Shade, "Shades" },
                { BuiltInCategory.OST_GbXML_SType_Exterior, "Exterior" },
                { BuiltInCategory.OST_GbXML_SType_Interior, "Interior" },
                { BuiltInCategory.OST_GbXMLFaces, "Analytical Surfaces" },
                { BuiltInCategory.OST_WireHomeRunArrows, "Home Run Arrows" },
                { BuiltInCategory.OST_LightingDeviceTags, "Lighting Device Tags" },
                { BuiltInCategory.OST_LightingDevices, "Lighting Devices" },
                { BuiltInCategory.OST_FireAlarmDeviceTags, "Fire Alarm Device Tags" },
                { BuiltInCategory.OST_FireAlarmDevices, "Fire Alarm Devices" },
                { BuiltInCategory.OST_DataDeviceTags, "Data Device Tags" },
                { BuiltInCategory.OST_DataDevices, "Data Devices" },
                { BuiltInCategory.OST_CommunicationDeviceTags, "Communication Device Tags" },
                { BuiltInCategory.OST_CommunicationDevices, "Communication Devices" },
                { BuiltInCategory.OST_SecurityDeviceTags, "Security Device Tags" },
                { BuiltInCategory.OST_SecurityDevices, "Security Devices" },
                { BuiltInCategory.OST_NurseCallDeviceTags, "Nurse Call Device Tags" },
                { BuiltInCategory.OST_NurseCallDevices, "Nurse Call Devices" },
                { BuiltInCategory.OST_TelephoneDeviceTags, "Telephone Device Tags" },
                { BuiltInCategory.OST_TelephoneDevices, "Telephone Devices" },
                { BuiltInCategory.OST_WireTickMarks, "Wire Tick Marks" },
                { BuiltInCategory.OST_PipeFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_PipeCurvesDrop, "Drop" },
                { BuiltInCategory.OST_DuctFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_DuctCurvesDrop, "Drop" },
                { BuiltInCategory.OST_DuctFittingTags, "Duct Fitting Tags" },
                { BuiltInCategory.OST_PipeFittingTags, "Pipe Fitting Tags" },
                { BuiltInCategory.OST_PipeColorFills, "Pipe Color Fill" },
                { BuiltInCategory.OST_PipeColorFillLegends, "Pipe Color Fill Legends" },
                { BuiltInCategory.OST_WireTags, "Wire Tags" },
                { BuiltInCategory.OST_PipeAccessoryTags, "Pipe Accessory Tags" },
                { BuiltInCategory.OST_PipeAccessory, "Pipe Accessories" },
                { BuiltInCategory.OST_PipeCurvesRiseDrop, "Rise" },
                { BuiltInCategory.OST_FlexPipeCurvesPattern, "Pattern" },
                { BuiltInCategory.OST_FlexPipeCurvesCenterLine, "Center Line" },
                { BuiltInCategory.OST_FlexPipeCurves, "Flex Pipes" },
                { BuiltInCategory.OST_PipeFitting, "Pipe Fittings" },
                { BuiltInCategory.OST_FlexPipeTags, "Flex Pipe Tags" },
                { BuiltInCategory.OST_PipeTags, "Pipe Tags" },
                { BuiltInCategory.OST_PipeCurvesCenterLine, "Center Line" },
                { BuiltInCategory.OST_PipeCurves, "Pipes" },
                { BuiltInCategory.OST_PipingSystem, "Piping Systems" },
                { BuiltInCategory.OST_Wire, "Wires" },
                { BuiltInCategory.OST_ElectricalCircuit, "Electrical Circuits" },
                { BuiltInCategory.OST_DuctCurvesRiseDrop, "Rise" },
                { BuiltInCategory.OST_FlexDuctCurvesPattern, "Pattern" },
                { BuiltInCategory.OST_FlexDuctCurvesCenterLine, "Center line" },
                { BuiltInCategory.OST_FlexDuctCurves, "Flex Ducts" },
                { BuiltInCategory.OST_DuctAccessoryTags, "Duct Accessory Tags" },
                { BuiltInCategory.OST_DuctAccessory, "Duct Accessories" },
                { BuiltInCategory.OST_DuctSystem, "Duct Systems" },
                { BuiltInCategory.OST_DuctTerminalTags, "Air Terminal Tags" },
                { BuiltInCategory.OST_DuctTerminal, "Air Terminals" },
                { BuiltInCategory.OST_DuctFitting, "Duct Fittings" },
                { BuiltInCategory.OST_DuctColorFills, "Duct Color Fill" },
                { BuiltInCategory.OST_FlexDuctTags, "Flex Duct Tags" },
                { BuiltInCategory.OST_DuctTags, "Duct Tags" },
                { BuiltInCategory.OST_DuctCurvesCenterLine, "Center line" },
                { BuiltInCategory.OST_DuctCurves, "Ducts" },
                { BuiltInCategory.OST_DuctColorFillLegends, "Duct Color Fill Legends" },
                { BuiltInCategory.OST_StructuralBracePlanReps, "Brace in Plan View Symbols" },
                { BuiltInCategory.OST_StructConnectionSymbols, "Connection Symbols" },
                { BuiltInCategory.OST_StructuralAnnotations, "Structural Annotations" },
                { BuiltInCategory.OST_RevisionCloudTags, "Revision Cloud Tags" },
                { BuiltInCategory.OST_RevisionClouds, "Revision Clouds" },
                { BuiltInCategory.OST_ElevationMarks, "Elevation Marks" },
                { BuiltInCategory.OST_GridHeads, "Grid Heads" },
                { BuiltInCategory.OST_LevelHeads, "Level Heads" },
                { BuiltInCategory.OST_VolumeOfInterest, "Scope Boxes" },
                { BuiltInCategory.OST_BoundaryConditions, "Boundary Conditions" },
                { BuiltInCategory.OST_InternalAreaLoadTags, "Internal Area Load Tags" },
                { BuiltInCategory.OST_InternalLineLoadTags, "Internal Line Load Tags" },
                { BuiltInCategory.OST_InternalPointLoadTags, "Internal Point Load Tags" },
                { BuiltInCategory.OST_AreaLoadTags, "Area Load Tags" },
                { BuiltInCategory.OST_LineLoadTags, "Line Load Tags" },
                { BuiltInCategory.OST_PointLoadTags, "Point Load Tags" },
                { BuiltInCategory.OST_LoadCasesSeismic, "Seismic Loads" },
                { BuiltInCategory.OST_LoadCasesTemperature, "Temperature Loads" },
                { BuiltInCategory.OST_LoadCasesAccidental, "Accidental Loads" },
                { BuiltInCategory.OST_LoadCasesRoofLive, "Roof Live Loads" },
                { BuiltInCategory.OST_LoadCasesSnow, "Snow Loads" },
                { BuiltInCategory.OST_LoadCasesWind, "Wind Loads" },
                { BuiltInCategory.OST_LoadCasesLive, "Live Loads" },
                { BuiltInCategory.OST_LoadCasesDead, "Dead Loads" },
                { BuiltInCategory.OST_LoadCases, "Structural Load Cases" },
                { BuiltInCategory.OST_InternalAreaLoads, "Internal Area Loads" },
                { BuiltInCategory.OST_InternalLineLoads, "Internal Line Loads" },
                { BuiltInCategory.OST_InternalPointLoads, "Internal Point Loads" },
                { BuiltInCategory.OST_InternalLoads, "Structural Internal Loads" },
                { BuiltInCategory.OST_AreaLoads, "Area Loads" },
                { BuiltInCategory.OST_LineLoads, "Line Loads" },
                { BuiltInCategory.OST_PointLoads, "Point Loads" },
                { BuiltInCategory.OST_Loads, "Structural Loads" },
                { BuiltInCategory.OST_BeamSystemTags, "Structural Beam System Tags" },
                { BuiltInCategory.OST_FootingSpanDirectionSymbol, "Foundation Span Direction Symbol" },
                { BuiltInCategory.OST_SpanDirectionSymbol, "Span Direction Symbol" },
                { BuiltInCategory.OST_SpotElevSymbols, "Spot Elevation Symbols" },
                { BuiltInCategory.OST_TrussTags, "Structural Truss Tags" },
                { BuiltInCategory.OST_KeynoteTags, "Keynote Tags" },
                { BuiltInCategory.OST_DetailComponentTags, "Detail Item Tags" },
                { BuiltInCategory.OST_MaterialTags, "Material Tags" },
                { BuiltInCategory.OST_FloorTags, "Floor Tags" },
                { BuiltInCategory.OST_CurtaSystemTags, "Curtain System Tags" },
                { BuiltInCategory.OST_StairsTags, "Stair Tags" },
                { BuiltInCategory.OST_MultiCategoryTags, "Multi-Category Tags" },
                { BuiltInCategory.OST_PlantingTags, "Planting Tags" },
                { BuiltInCategory.OST_AreaTags, "Area Tags" },
                { BuiltInCategory.OST_StructuralFoundationTags, "Structural Foundation Tags" },
                { BuiltInCategory.OST_StructuralColumnTags, "Structural Column Tags" },
                { BuiltInCategory.OST_ParkingTags, "Parking Tags" },
                { BuiltInCategory.OST_SiteTags, "Site Tags" },
                { BuiltInCategory.OST_StructuralFramingTags, "Structural Framing Tags" },
                { BuiltInCategory.OST_SpecialityEquipmentTags, "Specialty Equipment Tags" },
                { BuiltInCategory.OST_GenericModelTags, "Generic Model Tags" },
                { BuiltInCategory.OST_CurtainWallPanelTags, "Curtain Panel Tags" },
                { BuiltInCategory.OST_WallTags, "Wall Tags" },
                { BuiltInCategory.OST_PlumbingFixtureTags, "Plumbing Fixture Tags" },
                { BuiltInCategory.OST_MechanicalEquipmentTags, "Mechanical Equipment Tags" },
                { BuiltInCategory.OST_LightingFixtureTags, "Lighting Fixture Tags" },
                { BuiltInCategory.OST_FurnitureSystemTags, "Furniture System Tags" },
                { BuiltInCategory.OST_FurnitureTags, "Furniture Tags" },
                { BuiltInCategory.OST_ElectricalFixtureTags, "Electrical Fixture Tags" },
                { BuiltInCategory.OST_ElectricalEquipmentTags, "Electrical Equipment Tags" },
                { BuiltInCategory.OST_CeilingTags, "Ceiling Tags" },
                { BuiltInCategory.OST_CaseworkTags, "Casework Tags" },
                { BuiltInCategory.OST_MEPSpaceColorFill, "Color Fill" },
                { BuiltInCategory.OST_MEPSpaceReferenceVisibility, "Reference" },
                { BuiltInCategory.OST_MEPSpaceInteriorFillVisibility, "Interior" },
                { BuiltInCategory.OST_MEPSpaces, "Spaces" },
                { BuiltInCategory.OST_MassShade, "Mass Shade" },
                { BuiltInCategory.OST_MassOpening, "Mass Opening" },
                { BuiltInCategory.OST_MassSkylights, "Mass Skylight" },
                { BuiltInCategory.OST_MassGlazing, "Mass Glazing" },
                { BuiltInCategory.OST_MassRoof, "Mass Roof" },
                { BuiltInCategory.OST_MassExteriorWall, "Mass Exterior Wall" },
                { BuiltInCategory.OST_MassInteriorWall, "Mass Interior Wall" },
                { BuiltInCategory.OST_MassZone, "Mass Zone" },
                { BuiltInCategory.OST_MassAreaFaceTags, "Mass Floor Tags" },
                { BuiltInCategory.OST_HostTemplate, "Host Template" }, // TODO check if this category is valid
                { BuiltInCategory.OST_MassFaceSplitter, "Mass Face Splitter" }, // TODO check if this category is valid
                { BuiltInCategory.OST_MassCutter, "Mass Cutter" }, // TODO check if this category is valid
                { BuiltInCategory.OST_ZoningEnvelope, "Zoning Envelope" }, // TODO check if this category is valid
                { BuiltInCategory.OST_MassTags, "Mass Tags" },
                { BuiltInCategory.OST_MassForm, "Form" },
                { BuiltInCategory.OST_MassFloor, "Mass Floor" },
                { BuiltInCategory.OST_Mass, "Mass" },
                { BuiltInCategory.OST_DividedSurface_PatternFill, "Pattern Fill" },
                { BuiltInCategory.OST_DividedSurface_PatternLines, "Pattern Lines" },
                { BuiltInCategory.OST_DividedSurface_Gridlines, "Gridlines" },
                { BuiltInCategory.OST_DividedSurface_Nodes, "Nodes" },
                { BuiltInCategory.OST_RampsDownArrow, "Down Arrow" },
                { BuiltInCategory.OST_RampsUpArrow, "Up Arrow" },
                { BuiltInCategory.OST_RampsDownText, "DOWN text" },
                { BuiltInCategory.OST_RampsUpText, "UP text" },
                { BuiltInCategory.OST_RampsStringerAboveCut, "Stringers Beyond Cut Line" },
                { BuiltInCategory.OST_RampsStringer, "Stringers" },
                { BuiltInCategory.OST_RampsAboveCut, "Ramps Beyond Cut Line" },
                { BuiltInCategory.OST_Areas, "Areas" },
                { BuiltInCategory.OST_ProjectInformation, "Project Information" },
                { BuiltInCategory.OST_Sheets, "Sheets" },
                { BuiltInCategory.OST_DetailComponents, "Detail Items" },
                { BuiltInCategory.OST_RoofSoffit, "Roof Soffits" },
                { BuiltInCategory.OST_EdgeSlab, "Slab Edges" },
                { BuiltInCategory.OST_Gutter, "Gutters" },
                { BuiltInCategory.OST_Fascia, "Fascias" },
                { BuiltInCategory.OST_Entourage, "Entourage" },
                { BuiltInCategory.OST_Planting, "Planting" },
                { BuiltInCategory.OST_StructuralStiffenerHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructuralColumnLocationLine, "Location Lines" },
                { BuiltInCategory.OST_StructuralFramingLocationLine, "Location Lines" },
                { BuiltInCategory.OST_StructuralStiffenerTags, "Structural Stiffener Tags" },
                { BuiltInCategory.OST_StructuralStiffener, "Structural Stiffeners" },
                { BuiltInCategory.OST_SpecialityEquipment, "Specialty Equipment" },
                { BuiltInCategory.OST_ColumnAnalyticalRigidLinks, "Rigid Links" },
                { BuiltInCategory.OST_SecondaryTopographyContours, "Secondary Contours" },
                { BuiltInCategory.OST_TopographyContours, "Primary Contours" },
                { BuiltInCategory.OST_TopographySurface, "Triangulation Edges" },
                { BuiltInCategory.OST_Topography, "Topography" },
                { BuiltInCategory.OST_StructuralTruss, "Structural Trusses" },
                { BuiltInCategory.OST_StructuralColumnStickSymbols, "Stick Symbols" },
                { BuiltInCategory.OST_HiddenStructuralColumnLines, "Hidden Lines" },
                { BuiltInCategory.OST_AnalyticalRigidLinks, "Rigid Links" },
                { BuiltInCategory.OST_StructuralColumns, "Structural Columns" },
                { BuiltInCategory.OST_HiddenStructuralFramingLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructuralFramingSystem, "Structural Beam Systems" },
                { BuiltInCategory.OST_StructuralFraming, "Structural Framing" },
                { BuiltInCategory.OST_HiddenStructuralFoundationLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructuralFoundation, "Structural Foundations" },
                { BuiltInCategory.OST_SharedBasePoint, "Survey Point" },
                { BuiltInCategory.OST_ProjectBasePoint, "Project Base Point" },
                { BuiltInCategory.OST_SitePropertyLineSegmentTags, "Property Line Segment Tags" },
                { BuiltInCategory.OST_SitePropertyLineSegment, "Property Line Segments" },
                { BuiltInCategory.OST_SitePropertyTags, "Property Tags" },
                { BuiltInCategory.OST_SitePointBoundary, "Boundary Point" },
                { BuiltInCategory.OST_SiteProperty, "Property Lines" },
                { BuiltInCategory.OST_BuildingPad, "Pads" },
                { BuiltInCategory.OST_SitePoint, "Interior Point" },
                { BuiltInCategory.OST_Site, "Site" },
                { BuiltInCategory.OST_Roads, "Roads" },
                { BuiltInCategory.OST_Parking, "Parking" },
                { BuiltInCategory.OST_PlumbingFixtures, "Plumbing Fixtures" },
                { BuiltInCategory.OST_MechanicalEquipment, "Mechanical Equipment" },
                { BuiltInCategory.OST_LightingFixtureSource, "Light Source" },
                { BuiltInCategory.OST_LightingFixtures, "Lighting Fixtures" },
                { BuiltInCategory.OST_FurnitureSystems, "Furniture Systems" },
                { BuiltInCategory.OST_ElectricalFixtures, "Electrical Fixtures" },
                { BuiltInCategory.OST_ElectricalEquipment, "Electrical Equipment" },
                { BuiltInCategory.OST_Casework, "Casework" },
                { BuiltInCategory.OST_ShaftOpening, "Shaft Openings" },
                { BuiltInCategory.OST_FndSlabLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_FloorLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_WallLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_BraceLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_ColumnLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_BeamLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_MultiReferenceAnnotations, "Multi-Rebar Annotations" },
                { BuiltInCategory.OST_NodeAnalyticalTags, "Analytical Node Tags" },
                { BuiltInCategory.OST_LinkAnalyticalTags, "Analytical Link Tags" },
                { BuiltInCategory.OST_StairsSupports, "Supports" },
                { BuiltInCategory.OST_RailingHandRailAboveCut, "<Above> Handrails" },
                { BuiltInCategory.OST_RailingTopRailAboveCut, "<Above> Top Rails" },
                { BuiltInCategory.OST_RailingTermination, "Terminations" },
                { BuiltInCategory.OST_RailingSupport, "Supports" },
                { BuiltInCategory.OST_RailingHandRail, "Handrails" },
                { BuiltInCategory.OST_RailingTopRail, "Top Rails" },
                { BuiltInCategory.OST_StairsTriserNumbers, "Stair Tread/Riser Numbers" },
                { BuiltInCategory.OST_StairsSupportTags, "Stair Support Tags" },
                { BuiltInCategory.OST_StairsLandingTags, "Stair Landing Tags" },
                { BuiltInCategory.OST_StairsRunTags, "Stair Run Tags" },
                { BuiltInCategory.OST_StairsPathsAboveCut, "<Above> Up Arrows" },
                { BuiltInCategory.OST_StairsPaths, "Stair Paths" },
                { BuiltInCategory.OST_StairsRiserLinesAboveCut, "<Above> Riser Lines" },
                { BuiltInCategory.OST_StairsRiserLines, "Riser Lines" },
                { BuiltInCategory.OST_StairsOutlinesAboveCut, "<Above> Outlines" },
                { BuiltInCategory.OST_StairsOutlines, "Outlines" },
                { BuiltInCategory.OST_StairsNosingLinesAboveCut, "<Above> Nosing Lines" },
                { BuiltInCategory.OST_StairsNosingLines, "Nosing Lines" },
                { BuiltInCategory.OST_StairsCutMarksAboveCut, "<Above> Cut Marks" },
                { BuiltInCategory.OST_StairsCutMarks, "Cut Marks" },
                { BuiltInCategory.OST_StairsTrisers, "Treads/Risers" },
                { BuiltInCategory.OST_StairsLandings, "Landings" },
                { BuiltInCategory.OST_StairsRuns, "Runs" },
                { BuiltInCategory.OST_AdaptivePoints_Lines, "Lines" },
                { BuiltInCategory.OST_AdaptivePoints_Planes, "Planes" },
                { BuiltInCategory.OST_AdaptivePoints_Points, "Points" },
                { BuiltInCategory.OST_AdaptivePoints, "Adaptive Points" },
                { BuiltInCategory.OST_MEPSpaceSeparationLines, "<Space Separation>" },
                { BuiltInCategory.OST_InstanceDrivenLineStyle, "Instance Driven Line Style" }, // TODO check if this category is valid
                { BuiltInCategory.OST_ReferencePoints_Lines, "Lines" },
                { BuiltInCategory.OST_ReferencePoints_Planes, "Planes" },
                { BuiltInCategory.OST_ReferencePoints_Points, "Points" },
                { BuiltInCategory.OST_ReferencePoints, "Reference Points" },
                { BuiltInCategory.OST_Materials, "Materials" },
                { BuiltInCategory.OST_CeilingsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_CeilingsDefault, "Common Edges" },
                { BuiltInCategory.OST_CeilingsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_CeilingsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_CeilingsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_CeilingsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_CeilingsStructure, "Structure [1]" },
                { BuiltInCategory.OST_CeilingsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_FloorsInteriorEdges, "Interior Edges" },
                { BuiltInCategory.OST_FloorsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_HiddenFloorLines, "Hidden Lines" },
                { BuiltInCategory.OST_FloorsDefault, "Common Edges" },
                { BuiltInCategory.OST_FloorsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_FloorsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_FloorsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_FloorsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_FloorsStructure, "Structure [1]" },
                { BuiltInCategory.OST_FloorsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_RoofsInteriorEdges, "Interior Edges" },
                { BuiltInCategory.OST_RoofsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_RoofsDefault, "Common Edges" },
                { BuiltInCategory.OST_RoofsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_RoofsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_RoofsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_RoofsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_RoofsStructure, "Structure [1]" },
                { BuiltInCategory.OST_RoofsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_WallsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_HiddenWallLines, "Hidden Lines" },
                { BuiltInCategory.OST_WallsDefault, "Common Edges" },
                { BuiltInCategory.OST_WallsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_WallsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_WallsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_WallsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_WallsStructure, "Structure [1]" },
                { BuiltInCategory.OST_WallsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_ScheduleGraphics, "Schedule Graphics" },
                { BuiltInCategory.OST_RasterImages, "Raster Images" },
                { BuiltInCategory.OST_RoomColorFill, "Color Fill" },
                { BuiltInCategory.OST_ColorFillLegends, "Color Fill Legends" },
                { BuiltInCategory.OST_AnnotationCropSpecial, "Annotation Crop Boundary" },
                { BuiltInCategory.OST_CropBoundarySpecial, "Crop Boundaries" },
                { BuiltInCategory.OST_AnnotationCrop, "Annotation Crop Boundary" },
                { BuiltInCategory.OST_CalloutLeaderLine, "Callout Leader Line" },
                { BuiltInCategory.OST_CeilingsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_RoofsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_FloorsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_WallsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_CalloutBoundary, "Callout Boundary" },
                { BuiltInCategory.OST_CalloutHeads, "Callout Heads" },
                { BuiltInCategory.OST_Callouts, "Callouts" },
                { BuiltInCategory.OST_CropBoundary, "Crop Boundaries" },
                { BuiltInCategory.OST_Elev, "Elevations" },
                { BuiltInCategory.OST_CLines, "Reference Planes" },
                { BuiltInCategory.OST_ViewportLabel, "View Titles" },
                { BuiltInCategory.OST_Viewports, "Viewports" },
                { BuiltInCategory.OST_Camera_Lines, "Cameras" },
                { BuiltInCategory.OST_MEPSpaceTags, "Space Tags" },
                { BuiltInCategory.OST_RoomTags, "Room Tags" },
                { BuiltInCategory.OST_DoorTags, "Door Tags" },
                { BuiltInCategory.OST_WindowTags, "Window Tags" },
                { BuiltInCategory.OST_SectionHeadWideLines, "Wide Lines" },
                { BuiltInCategory.OST_SectionHeadMediumLines, "Medium Lines" },
                { BuiltInCategory.OST_SectionHeadThinLines, "Thin Lines" },
                { BuiltInCategory.OST_SectionHeads, "Section Marks" },
                { BuiltInCategory.OST_ContourLabels, "Contour Labels" },
                { BuiltInCategory.OST_CurtaSystem, "Curtain Systems" },
                { BuiltInCategory.OST_CurtainGridsCurtaSystem, "Curtain System Grids" },
                { BuiltInCategory.OST_CurtainGridsSystem, "Curtain Grids System" }, // TODO check if this category is valid
                { BuiltInCategory.OST_CurtainGridsWall, "Curtain Wall Grids" },
                { BuiltInCategory.OST_CurtainGridsRoof, "Curtain Roof Grids" },
                { BuiltInCategory.OST_AnalysisDisplayStyle, "Analysis Display Style" },
                { BuiltInCategory.OST_AnalysisResults, "Analysis Results" },
                { BuiltInCategory.OST_RenderRegions, "Render Regions" },
                { BuiltInCategory.OST_SectionBox, "Section Boxes" },
                { BuiltInCategory.OST_TextNotes, "Text Notes" },
                { BuiltInCategory.OST_CenterLines, "<Centerline>" },
                { BuiltInCategory.OST_LinesBeyond, "<Beyond>" },
                { BuiltInCategory.OST_HiddenLines, "<Hidden>" },
                { BuiltInCategory.OST_DemolishedLines, "<Demolished>" },
                { BuiltInCategory.OST_OverheadLines, "<Overhead>" },
                { BuiltInCategory.OST_TitleBlockWideLines, "Wide Lines" },
                { BuiltInCategory.OST_TitleBlockMediumLines, "Medium Lines" },
                { BuiltInCategory.OST_TitleBlockThinLines, "Thin Lines" },
                { BuiltInCategory.OST_TitleBlocks, "Title Blocks" },
                { BuiltInCategory.OST_Views, "Views" },
                { BuiltInCategory.OST_PartHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_PartTags, "Part Tags" },
                { BuiltInCategory.OST_Parts, "Parts" },
                { BuiltInCategory.OST_AssemblyTags, "Assembly Tags" },
                { BuiltInCategory.OST_Assemblies, "Assemblies" },
                { BuiltInCategory.OST_RoofTags, "Roof Tags" },
                { BuiltInCategory.OST_SpotSlopes, "Spot Slopes" },
                { BuiltInCategory.OST_SpotCoordinates, "Spot Coordinates" },
                { BuiltInCategory.OST_SpotElevations, "Spot Elevations" },
                { BuiltInCategory.OST_WeakDims, "Automatic Sketch Dimensions" },
                { BuiltInCategory.OST_Dimensions, "Dimensions" },
                { BuiltInCategory.OST_Levels, "Levels" },
                { BuiltInCategory.OST_DisplacementPath, "Displacement Path" },
                { BuiltInCategory.OST_GridChains, "Multi-segmented Grid" },
                { BuiltInCategory.OST_Grids, "Grids" },
                { BuiltInCategory.OST_BrokenSectionLine, "Broken Section Line" },
                { BuiltInCategory.OST_SectionLine, "Section Line" },
                { BuiltInCategory.OST_Sections, "Sections" },
                { BuiltInCategory.OST_ReferenceViewer, "View Reference" },
                { BuiltInCategory.OST_ReferenceViewerSymbol, "View Reference" },
                { BuiltInCategory.OST_ImportObjectStyles, "Imports in Families" },
                { BuiltInCategory.OST_MaskingRegion, "Masking Region" },
                { BuiltInCategory.OST_Matchline, "Matchline" },
                { BuiltInCategory.OST_PlanRegion, "Plan Region" },
                { BuiltInCategory.OST_FilledRegion, "Filled region" },
                { BuiltInCategory.OST_Cornices, "Wall Sweeps" },
                { BuiltInCategory.OST_Ramps, "Ramps" },
                { BuiltInCategory.OST_CurtainGrids, "Curtain Grids" },
                { BuiltInCategory.OST_CurtainWallMullions, "Curtain Wall Mullions" },
                { BuiltInCategory.OST_CurtainWallPanels, "Curtain Panels" },
                { BuiltInCategory.OST_AreaColorFill, "Color Fill" },
                { BuiltInCategory.OST_AreaReferenceVisibility, "Reference" },
                { BuiltInCategory.OST_AreaInteriorFillVisibility, "Interior Fill" },
                { BuiltInCategory.OST_RoomReferenceVisibility, "Reference" },
                { BuiltInCategory.OST_RoomInteriorFillVisibility, "Interior Fill" },
                { BuiltInCategory.OST_Rooms, "Rooms" },
                { BuiltInCategory.OST_GenericModel, "Generic Models" },
                { BuiltInCategory.OST_GenericAnnotation, "Generic Annotations" },
                { BuiltInCategory.OST_StairsRailingTags, "Railing Tags" },
                { BuiltInCategory.OST_StairsRailingAboveCut, "<Above> Railings Cut Line" },
                { BuiltInCategory.OST_StairsDownArrows, "Down Arrows" },
                { BuiltInCategory.OST_StairsUpArrows, "Up Arrows" },
                { BuiltInCategory.OST_StairsDownText, "DOWN Text" },
                { BuiltInCategory.OST_StairsRailingRail, "Rails" },
                { BuiltInCategory.OST_StairsRailingBaluster, "Balusters" },
                { BuiltInCategory.OST_StairsRailing, "Railings" },
                { BuiltInCategory.OST_StairsUpText, "UP Text" },
                { BuiltInCategory.OST_StairsSupportsAboveCut, "<Above> Supports" },
                { BuiltInCategory.OST_StairsStringerCarriage, "Supports" },
                { BuiltInCategory.OST_Stairs, "Stairs" },
                { BuiltInCategory.OST_GuideGrid, "Guide Grid" },
                { BuiltInCategory.OST_Columns, "Columns" },
                { BuiltInCategory.OST_ReferenceLines, "Reference Lines" },
                { BuiltInCategory.OST_IOSNotSilhouette, "IOS Not Silhouette" }, // TODO check if this category is valid
                { BuiltInCategory.OST_Furniture, "Furniture" },
                { BuiltInCategory.OST_AreaSchemeLines, "<Area Boundary>" },
                { BuiltInCategory.OST_GenericLines, "Lines" },
                { BuiltInCategory.OST_InsulationLines, "Insulation Batting Lines" },
                { BuiltInCategory.OST_RoomSeparationLines, "<Room Separation>" },
                { BuiltInCategory.OST_AxisOfRotation, "Axis of Rotation" },
                { BuiltInCategory.OST_InvisibleLines, "Invisible Lines" }, // TODO check if this category is valid
                { BuiltInCategory.OST_Lines, "Lines" },
                { BuiltInCategory.OST_SketchLines, "<Sketch>" },
                { BuiltInCategory.OST_CurvesWideLines, "Wide Lines" },
                { BuiltInCategory.OST_CurvesMediumLines, "Medium Lines" },
                { BuiltInCategory.OST_CurvesThinLines, "Thin Lines" },
                { BuiltInCategory.OST_Ceilings, "Ceilings" },
                { BuiltInCategory.OST_Roofs, "Roofs" },
                { BuiltInCategory.OST_Floors, "Floors" },
                { BuiltInCategory.OST_DoorsGlassProjection, "Glass" },
                { BuiltInCategory.OST_DoorsFrameMullionProjection, "Frame/Mullion" },
                { BuiltInCategory.OST_DoorsOpeningProjection, "Opening" },
                { BuiltInCategory.OST_DoorsPanelProjection, "Panel" },
                { BuiltInCategory.OST_Doors, "Doors" },
                { BuiltInCategory.OST_WindowsOpeningProjection, "Opening" },
                { BuiltInCategory.OST_WindowsSillHeadProjection, "Sill/Head" },
                { BuiltInCategory.OST_WindowsFrameMullionProjection, "Frame/Mullion" },
                { BuiltInCategory.OST_WindowsGlassProjection, "Glass" },
                { BuiltInCategory.OST_Windows, "Windows" },
                { BuiltInCategory.OST_Walls, "Walls" },
            };
        }

        /// <summary>
        /// Tries to get the name of a built-in category.
        /// </summary>
        /// <param name="category">The category.</param>
        /// <param name="categoryName">Name of the category.</param>
        /// <returns></returns>
        public static bool TryGetCategoryName(this BuiltInCategory category, out string categoryName)
        {
            return knownCategories.TryGetValue(category, out categoryName);
        }
    }
}