#pragma warning disable CS0618 // Type or member is obsolete

using System;
using System.Collections.Generic;
using System.Linq;

namespace CodeCave.Revit.Toolkit
{
    /// <summary>
    /// Contains extension methods for <see cref="UnitSymbolType"/>.
    /// </summary>
    public static class UnitSymbolTypeExtensions
    {
        private static readonly Dictionary<UnitSymbolType, string> unitSymbolTypes;

        /// <summary>
        /// Initializes static members of the <see cref="UnitSymbolTypeExtensions"/> class.
        /// Initializes the <see cref="UnitSymbolTypeExtensions"/> class.
        /// </summary>
        static UnitSymbolTypeExtensions()
        {
            unitSymbolTypes = new Dictionary<UnitSymbolType, string>
            {
                { UnitSymbolType.UST_NONE, string.Empty },
                { UnitSymbolType.UST_M, "m" },
                { UnitSymbolType.UST_CM, "cm" },
                { UnitSymbolType.UST_MM, "mm" },
                { UnitSymbolType.UST_LF, "LF" },
                { UnitSymbolType.UST_FOOT_SINGLE_QUOTE, "'" },
                { UnitSymbolType.UST_FT, "ft" },
                { UnitSymbolType.UST_INCH_DOUBLE_QUOTE, "\"" },
                { UnitSymbolType.UST_IN, "in" },
                { UnitSymbolType.UST_ACRES, "acres" },
                { UnitSymbolType.UST_HECTARES, "hectare" },
                { UnitSymbolType.UST_CY, "CY" },
                { UnitSymbolType.UST_SF, "SF" },
                { UnitSymbolType.UST_FT_SUP_2, "ft²" },
                { UnitSymbolType.UST_FT_CARET_2, "ft^2" },
                { UnitSymbolType.UST_M_SUP_2, "m²" },
                { UnitSymbolType.UST_M_CARET_2, "m^2" },
                { UnitSymbolType.UST_CF, "CF" },
                { UnitSymbolType.UST_FT_SUP_3, "ft³" },
                { UnitSymbolType.UST_FT_CARET_3, "ft^3" },
                { UnitSymbolType.UST_M_SUP_3, "m³" },
                { UnitSymbolType.UST_M_CARET_3, "m^3" },
                { UnitSymbolType.UST_DEGREE_SYMBOL, "°" },
                { UnitSymbolType.UST_PERCENT_SIGN, "%" },
                { UnitSymbolType.UST_IN_SUP_2, "in²" },
                { UnitSymbolType.UST_IN_CARET_2, "in^2" },
                { UnitSymbolType.UST_CM_SUP_2, "cm²" },
                { UnitSymbolType.UST_CM_CARET_2, "cm^2" },
                { UnitSymbolType.UST_MM_SUP_2, "mm²" },
                { UnitSymbolType.UST_MM_CARET_2, "mm^2" },
                { UnitSymbolType.UST_IN_SUP_3, "in³" },
                { UnitSymbolType.UST_IN_CARET_3, "in^3" },
                { UnitSymbolType.UST_CM_SUP_3, "cm³" },
                { UnitSymbolType.UST_CM_CARET_3, "cm^3" },
                { UnitSymbolType.UST_MM_SUP_3, "mm³" },
                { UnitSymbolType.UST_MM_CARET_3, "mm^3" },
                { UnitSymbolType.UST_L, "L" },
                { UnitSymbolType.UST_GAL, "gal" },
                { UnitSymbolType.UST_KG_PER_CU_M, "kg/m³" },
                { UnitSymbolType.UST_LB_MASS_PER_CU_FT, "lb/ft³" },
                { UnitSymbolType.UST_LBM_PER_CU_FT, "lbm/ft³" },
                { UnitSymbolType.UST_LB_MASS_PER_CU_IN, "lb/in³" },
                { UnitSymbolType.UST_LBM_PER_CU_IN, "lbm/in³" },
                { UnitSymbolType.UST_BTU, "Btu" },
                { UnitSymbolType.UST_CAL, "cal" },
                { UnitSymbolType.UST_KCAL, "kcal" },
                { UnitSymbolType.UST_JOULE, "J" },
                { UnitSymbolType.UST_KWH, "kWh" },
                { UnitSymbolType.UST_THERM, "therm" },
                { UnitSymbolType.UST_IN_WG_PER_100FT, "in-wg/100ft" },
                { UnitSymbolType.UST_PASCAL_PER_M, "Pa/m" },
                { UnitSymbolType.UST_WATT, "W" },
                { UnitSymbolType.UST_KILOWATT, "kW" },
                { UnitSymbolType.UST_BTU_PER_S, "Btu/s" },
                { UnitSymbolType.UST_BTU_PER_H, "Btu/h" },
                { UnitSymbolType.UST_CAL_PER_S, "cal/s" },
                { UnitSymbolType.UST_KCAL_PER_S, "kcal/s" },
                { UnitSymbolType.UST_WATT_PER_SQ_FT, "W/ft²" },
                { UnitSymbolType.UST_WATT_PER_SQ_M, "W/m²" },
                { UnitSymbolType.UST_IN_WG, "in-wg" },
                { UnitSymbolType.UST_PASCAL, "Pa" },
                { UnitSymbolType.UST_KILOPASCAL, "kPa" },
                { UnitSymbolType.UST_MEGAPASCAL, "MPa" },
                { UnitSymbolType.UST_PSI, "psi" },
                { UnitSymbolType.UST_LB_FORCE_PER_SQ_IN, "lb/in²" },
                { UnitSymbolType.UST_PSIG, "psig" },
                { UnitSymbolType.UST_PSIA, "psia" },
                { UnitSymbolType.UST_LBF_PER_SQ_IN, "lbf/in²" },
                { UnitSymbolType.UST_IN_HG, "inHg" },
                { UnitSymbolType.UST_MM_HG, "mmHg" },
                { UnitSymbolType.UST_ATM, "atm" },
                { UnitSymbolType.UST_BAR, "bar" },
                { UnitSymbolType.UST_DEGREE_F, "°F" },
                { UnitSymbolType.UST_DEGREE_C, "°C" },
                { UnitSymbolType.UST_KELVIN, "K" },
                { UnitSymbolType.UST_DEGREE_R, "°R" },
                { UnitSymbolType.UST_FT_PER_MIN, "ft/min" },
                { UnitSymbolType.UST_FPM, "FPM" },
                { UnitSymbolType.UST_M_PER_S, "m/s" },
                { UnitSymbolType.UST_CM_PER_MIN, "cm/min" },
                { UnitSymbolType.UST_CU_FT_PER_MIN, "ft³/min" },
                { UnitSymbolType.UST_CFM, "CFM" },
                { UnitSymbolType.UST_L_PER_S, "L/s" },
                { UnitSymbolType.UST_LPS, "LPS" },
                { UnitSymbolType.UST_CU_M_PER_S, "m³/s" },
                { UnitSymbolType.UST_CMS, "CMS" },
                { UnitSymbolType.UST_CU_M_PER_H, "m³/h" },
                { UnitSymbolType.UST_CMH, "CMH" },
                { UnitSymbolType.UST_GAL_PER_MIN, "gal/min" },
                { UnitSymbolType.UST_GPM, "GPM" },
                { UnitSymbolType.UST_USGPM, "usgpm" },
                { UnitSymbolType.UST_GAL_PER_H, "gal/h" },
                { UnitSymbolType.UST_GPH, "GPH" },
                { UnitSymbolType.UST_USGPH, "usgph" },
                { UnitSymbolType.UST_AMPERE, "A" },
                { UnitSymbolType.UST_KILOAMPERE, "kA" },
                { UnitSymbolType.UST_MILLIAMPERE, "mA" },
                { UnitSymbolType.UST_VOLT, "V" },
                { UnitSymbolType.UST_KILOVOLT, "kV" },
                { UnitSymbolType.UST_MILLIVOLT, "mV" },
                { UnitSymbolType.UST_HZ, "Hz" },
                { UnitSymbolType.UST_CPS, "cps" },
                { UnitSymbolType.UST_LX, "lx" },
                { UnitSymbolType.UST_FC, "fc" },
                { UnitSymbolType.UST_FTC, "Ftc" },
                { UnitSymbolType.UST_FL, "fL" },
                { UnitSymbolType.UST_FL_LOWERCASE, "fl" },
                { UnitSymbolType.UST_FTL, "ftL" },
                { UnitSymbolType.UST_CD_PER_SQ_M, "cd/m²" },
                { UnitSymbolType.UST_CD, "cd" },
                { UnitSymbolType.UST_LM, "lm" },
                { UnitSymbolType.UST_VOLTAMPERE, "VA" },
                { UnitSymbolType.UST_KILOVOLTAMPERE, "kVA" },
                { UnitSymbolType.UST_HP, "hp" },
                { UnitSymbolType.UST_N, "N" },
                { UnitSymbolType.UST_DA_N, "daN" },
                { UnitSymbolType.UST_K_N, "kN" },
                { UnitSymbolType.UST_M_N, "MN" },
                { UnitSymbolType.UST_KIP, "kip" },
                { UnitSymbolType.UST_KGF, "kgf" },
                { UnitSymbolType.UST_TF, "Tf" },
                { UnitSymbolType.UST_LBF, "lbf" },
                { UnitSymbolType.UST_N_PER_M, "N/m" },
                { UnitSymbolType.UST_DA_N_PER_M, "daN/m" },
                { UnitSymbolType.UST_K_N_PER_M, "kN/m" },
                { UnitSymbolType.UST_M_N_PER_M, "MN/m" },
                { UnitSymbolType.UST_KIP_PER_FT, "kip/ft" },
                { UnitSymbolType.UST_KGF_PER_M, "kgf/m" },
                { UnitSymbolType.UST_TF_PER_M, "Tf/m" },
                { UnitSymbolType.UST_LB_FORCE_PER_FT, "lb/ft" },
                { UnitSymbolType.UST_LBF_PER_FT, "lbf/ft" },
                { UnitSymbolType.UST_N_PER_M_SUP_2, "N/m²" },
                { UnitSymbolType.UST_DA_N_PER_M_SUP_2, "daN/m²" },
                { UnitSymbolType.UST_K_N_PER_M_SUP_2, "kN/m²" },
                { UnitSymbolType.UST_M_N_PER_M_SUP_2, "MN/m²" },
                { UnitSymbolType.UST_KSF, "ksf" },
                { UnitSymbolType.UST_KIP_PER_SQ_FT, "kip/ft²" },
                { UnitSymbolType.UST_KGF_PER_M_SUP_2, "kgf/m²" },
                { UnitSymbolType.UST_TF_PER_M_SUP_2, "Tf/m²" },
                { UnitSymbolType.UST_PSF, "psf" },
                { UnitSymbolType.UST_LB_FORCE_PER_SQ_FT, "lb/ft²" },
                { UnitSymbolType.UST_LBF_PER_SQ_FT, "lbf/ft²" },
                { UnitSymbolType.UST_N_DASH_M, "N-m" },
                { UnitSymbolType.UST_DA_N_DASH_M, "daN-m" },
                { UnitSymbolType.UST_K_N_DASH_M, "kN-m" },
                { UnitSymbolType.UST_M_N_DASH_M, "MN-m" },
                { UnitSymbolType.UST_KIP_DASH_FT, "kip-ft" },
                { UnitSymbolType.UST_KGF_DASH_M, "kgf-m" },
                { UnitSymbolType.UST_TF_DASH_M, "Tf-m" },
                { UnitSymbolType.UST_LB_FORCE_DASH_FT, "lb-ft" },
                { UnitSymbolType.UST_LBF_DASH_FT, "lbf-ft" },
                { UnitSymbolType.UST_M_PER_K_N, "m/kN" },
                { UnitSymbolType.UST_FT_PER_KIP, "ft/kip" },
                { UnitSymbolType.UST_M_SUP_2_PER_K_N, "m²/kN" },
                { UnitSymbolType.UST_FT_SUP_2_PER_KIP, "ft²/kip" },
                { UnitSymbolType.UST_M_SUP_3_PER_K_N, "m³/kN" },
                { UnitSymbolType.UST_FT_SUP_3_PER_KIP, "ft³/kip" },
                { UnitSymbolType.UST_INV_K_N, "1/kN" },
                { UnitSymbolType.UST_INV_KIP, "1/kip" },
                { UnitSymbolType.UST_FTH2O_PER_100FT, "ftH2O/100ft" },
                { UnitSymbolType.UST_FT_OF_WATER_PER_100FT, "FT/100ft" },
                { UnitSymbolType.UST_FEET_OF_WATER_PER_100FT, "Feet/100ft" },
                { UnitSymbolType.UST_FTH2O, "ftH2O" },
                { UnitSymbolType.UST_FT_OF_WATER, "FT" },
                { UnitSymbolType.UST_FEET_OF_WATER, "Feet" },
                { UnitSymbolType.UST_PA_S, "Pa-s" },
                { UnitSymbolType.UST_LB_FORCE_PER_FT_S, "lb/ft-s" },
                { UnitSymbolType.UST_LBM_PER_FT_S, "lbm/ft-s" },
                { UnitSymbolType.UST_CP, "cP" },
                { UnitSymbolType.UST_FT_PER_S, "ft/s" },
                { UnitSymbolType.UST_FPS, "FPS" },
                { UnitSymbolType.UST_KSI, "ksi" },
                { UnitSymbolType.UST_KIP_PER_SQ_IN, "kip/in²" },
                { UnitSymbolType.UST_KN_PER_M_SUP_3, "kN/m³" },
                { UnitSymbolType.UST_LB_FORCE_PER_CU_FT, "lb/ft³" },
                { UnitSymbolType.UST_LBF_PER_CU_FT, "lbf/ft³" },
                { UnitSymbolType.UST_KIP_PER_IN_SUP_3, "kip/in³" },
                { UnitSymbolType.UST_INV_DEGREE_F, "1/°F" },
                { UnitSymbolType.UST_INV_DEGREE_C, "1/°C" },
                { UnitSymbolType.UST_N_DASH_M_PER_M, "N-m/m" },
                { UnitSymbolType.UST_DA_N_DASH_M_PER_M, "daN-m/m" },
                { UnitSymbolType.UST_K_N_DASH_M_PER_M, "kN-m/m" },
                { UnitSymbolType.UST_M_N_DASH_M_PER_M, "MN-m/m" },
                { UnitSymbolType.UST_KIP_DASH_FT_PER_FT, "kip-ft/ft" },
                { UnitSymbolType.UST_KGF_DASH_M_PER_M, "kgf-m/m" },
                { UnitSymbolType.UST_TF_DASH_M_PER_M, "Tf-m/m" },
                { UnitSymbolType.UST_LB_FORCE_DASH_FT_PER_FT, "lb-ft/ft" },
                { UnitSymbolType.UST_LBF_DASH_FT_PER_FT, "lbf-ft/ft" },
                { UnitSymbolType.UST_LB_FORCE_PER_FT_H, "lb/ft-h" },
                { UnitSymbolType.UST_LBM_PER_FT_H, "lbm/ft-h" },
                { UnitSymbolType.UST_KIPS_PER_IN, "kip/in" },
                { UnitSymbolType.UST_KIPS_PER_CU_FT, "kip/ft³" },
                { UnitSymbolType.UST_KIP_FT_PER_DEGREE, "kip-ft/°" },
                { UnitSymbolType.UST_K_N_M_PER_DEGREE, "kN-m/°" },
                { UnitSymbolType.UST_KIP_FT_PER_DEGREE_PER_FT, "kip-ft/°/ft" },
                { UnitSymbolType.UST_K_N_M_PER_DEGREE_PER_M, "kN-m/°/m" },
                { UnitSymbolType.UST_WATT_PER_SQ_M_K, "W/(m²·K)" },
                { UnitSymbolType.UST_BTU_PER_H_SQ_FT_DEGREE_F, "BTU/(h·ft²·°F)" },
                { UnitSymbolType.UST_CFM_PER_SQ_FT, "CFM/ft²" },
                { UnitSymbolType.UST_CFM_PER_SF, "CFM/SF" },
                { UnitSymbolType.UST_LPS_PER_SQ_M, "LPS/m²" },
                { UnitSymbolType.UST_L_PER_S_SQ_M, "L/(s·m²)" },
                { UnitSymbolType.UST_COLON_10, ":10" },
                { UnitSymbolType.UST_COLON_12, ":12" },
                { UnitSymbolType.UST_SLOPE_DEGREE_SYMBOL, "°" },
                { UnitSymbolType.UST_WATT_PER_CU_FT, "W/ft³" },
                { UnitSymbolType.UST_WATT_PER_CU_M, "W/m³" },
                { UnitSymbolType.UST_BTU_PER_H_SQ_FT, "Btu/(h·ft²)" },
                { UnitSymbolType.UST_BTU_PER_H_CU_FT, "Btu/(h·ft³)" },
                { UnitSymbolType.UST_TON, "ton" },
                { UnitSymbolType.UST_TON_OF_REFRIGERATION, "ton of refrigeration" },
                { UnitSymbolType.UST_CFM_PER_CU_FT, "CFM/ft³" },
                { UnitSymbolType.UST_CFM_PER_CF, "CFM/CF" },
                { UnitSymbolType.UST_L_PER_S_CU_M, "L/(s·m³)" },
                { UnitSymbolType.UST_CFM_PER_TON, "CFM/ton" },
                { UnitSymbolType.UST_L_PER_S_KW, "L/(s·kW)" },
                { UnitSymbolType.UST_SQ_FT_PER_TON, "ft²/ton" },
                { UnitSymbolType.UST_SF_PER_TON, "SF/ton" },
                { UnitSymbolType.UST_SQ_M_PER_KW, "m²/kW" },
                { UnitSymbolType.UST_DOLLAR, "$" },
                { UnitSymbolType.UST_EURO_SUFFIX, "€" },
                { UnitSymbolType.UST_EURO_PREFIX, "€" },
                { UnitSymbolType.UST_POUND, "£" },
                { UnitSymbolType.UST_YEN, "¥" },
                { UnitSymbolType.UST_CHINESE_HONG_KONG_SAR, "HK$" },
                { UnitSymbolType.UST_WON, "₩" },
                { UnitSymbolType.UST_SHEQEL, "₪" },
                { UnitSymbolType.UST_DONG, "₫" },
                { UnitSymbolType.UST_BAHT, "฿" },
                { UnitSymbolType.UST_KRONER, "kr" },
                { UnitSymbolType.UST_LM_PER_W, "lm/W" },
                { UnitSymbolType.UST_SF_PER_MBH, "SF/MBh" },
                { UnitSymbolType.UST_SF_PER_KBTU_PER_H, "SF·h/kBtu" },
                { UnitSymbolType.UST_SQ_FT_PER_MBH, "ft²/MBh" },
                { UnitSymbolType.UST_SQ_FT_PER_KBTU_PER_H, "ft²·h/kBtu" },
                { UnitSymbolType.UST_K_N_PER_CM_SUP_2, "kN/cm²" },
                { UnitSymbolType.UST_N_PER_MM_SUP_2, "N/mm²" },
                { UnitSymbolType.UST_K_N_PER_MM_SUP_2, "kN/mm²" },
                { UnitSymbolType.UST_ONE_COLON, "0,0416666666666667" },
                { UnitSymbolType.UST_H_SQ_FT_DEGREE_F_PER_BTU, "(h·ft²·°F)/BTU" },
                { UnitSymbolType.UST_SQ_M_K_PER_WATT, "(m²·K)/W" },
                { UnitSymbolType.UST_BTU_PER_F, "BTU/°F" },
                { UnitSymbolType.UST_J_PER_KELVIN, "J/K" },
                { UnitSymbolType.UST_KJ_PER_KELVIN, "kJ/K" },
                { UnitSymbolType.UST_KGM, "kg" },
                { UnitSymbolType.UST_TM, "t" },
                { UnitSymbolType.UST_LB_MASS, "lb" },
                { UnitSymbolType.UST_LBM, "lbm" },
                { UnitSymbolType.UST_M_PER_SQ_S, "m/s²" },
                { UnitSymbolType.UST_KM_PER_SQ_S, "km/s²" },
                { UnitSymbolType.UST_IN_PER_SQ_S, "in/s²" },
                { UnitSymbolType.UST_FT_PER_SQ_S, "ft/s²" },
                { UnitSymbolType.UST_MI_PER_SQ_S, "mi/s²" },
                { UnitSymbolType.UST_FT_SUP_4, "ft4" },
                { UnitSymbolType.UST_IN_SUP_4, "in4" },
                { UnitSymbolType.UST_MM_SUP_4, "mm4" },
                { UnitSymbolType.UST_CM_SUP_4, "cm4" },
                { UnitSymbolType.UST_M_SUP_4, "m4" },
                { UnitSymbolType.UST_FT_SUP_6, "ft6" },
                { UnitSymbolType.UST_IN_SUP_6, "in6" },
                { UnitSymbolType.UST_MM_SUP_6, "mm6" },
                { UnitSymbolType.UST_CM_SUP_6, "cm6" },
                { UnitSymbolType.UST_M_SUP_6, "m6" },
                { UnitSymbolType.UST_SQ_FT_PER_FT, "ft²/ft" },
                { UnitSymbolType.UST_SQ_IN_PER_FT, "in²/ft" },
                { UnitSymbolType.UST_SQ_MM_PER_M, "mm²/m" },
                { UnitSymbolType.UST_SQ_CM_PER_M, "cm²/m" },
                { UnitSymbolType.UST_SQ_M_PER_M, "m²/m" },
                { UnitSymbolType.UST_KGM_PER_M, "kg/m" },
                { UnitSymbolType.UST_LB_MASS_PER_FT, "lb/ft" },
                { UnitSymbolType.UST_LBM_PER_FT, "lbm/ft" },
                { UnitSymbolType.UST_RAD, "rad" },
                { UnitSymbolType.UST_GRAD, "grad" },
                { UnitSymbolType.UST_RAD_PER_S, "rad/s" },
                { UnitSymbolType.UST_MS, "ms" },
                { UnitSymbolType.UST_S, "s" },
                { UnitSymbolType.UST_MIN, "min" },
                { UnitSymbolType.UST_H, "h" },
                { UnitSymbolType.UST_KM_PER_H, "km/h" },
                { UnitSymbolType.UST_MI_PER_H, "mph" },
                { UnitSymbolType.UST_KJ, "kJ" },
                { UnitSymbolType.UST_KGM_PER_SQ_M, "kg/m²" },
                { UnitSymbolType.UST_LBM_PER_SQ_FT, "lb/ft²" },
                { UnitSymbolType.UST_WATTS_PER_METER_KELVIN, "W/(m·K)" },
                { UnitSymbolType.UST_J_PER_G_CELSIUS, "J/(g·°C)" },
                { UnitSymbolType.UST_J_PER_G, "J/g" },
                { UnitSymbolType.UST_NG_PER_PA_S_SQ_M, "ng/(Pa·s·m²)" },
                { UnitSymbolType.UST_OHM_M, "ohm·m" },
                { UnitSymbolType.UST_BTU_PER_H_FT_DEGREE_F, "BTU/(h·ft·°F)" },
                { UnitSymbolType.UST_BTU_PER_LB_DEGREE_F, "BTU/(lb·°F)" },
                { UnitSymbolType.UST_BTU_PER_LB, "BTU/lb" },
                { UnitSymbolType.UST_GR_PER_H_SQ_FT_IN_HG, "gr/(h·ft²·inHg)" },
                { UnitSymbolType.UST_PER_MILLE_SIGN, "‰" },
                { UnitSymbolType.UST_DM, "dm" },
                { UnitSymbolType.UST_J_PER_KG_CELSIUS, "J/(kg·°C)" },
                { UnitSymbolType.UST_UM_PER_M_C, "µm/(m·°C)" },
                { UnitSymbolType.UST_UIN_PER_IN_F, "µin/(in·°F)" },
                { UnitSymbolType.UST_USTONNES_MASS_TONS, "Tons" },
                { UnitSymbolType.UST_USTONNES_MASS_T, "T" },
                { UnitSymbolType.UST_USTONNES_MASS_ST, "ST" },
                { UnitSymbolType.UST_USTONNES_FORCE_TONSF, "Tonsf" },
                { UnitSymbolType.UST_USTONNES_FORCE_STF, "STf" },
                { UnitSymbolType.UST_USTONNES_FORCE_AS_MASS_TONS, "Tons" },
                { UnitSymbolType.UST_USTONNES_FORCE_AS_MASS_T, "T" },
                { UnitSymbolType.UST_USTONNES_FORCE_AS_MASS_ST, "ST" },
                { UnitSymbolType.UST_L_PER_M, "L/min" },
                { UnitSymbolType.UST_LPM, "LPM" },
                { UnitSymbolType.UST_DEGREE_F_DIFFERENCE, "°F" },
                { UnitSymbolType.UST_DELTA_DEGREE_F, "delta°F" },
                { UnitSymbolType.UST_DEGREE_C_DIFFERENCE, "°C" },
                { UnitSymbolType.UST_DELTA_DEGREE_C, "delta°C" },
                { UnitSymbolType.UST_KELVIN_DIFFERENCE, "K" },
                { UnitSymbolType.UST_DELTA_KELVIN, "deltaK" },
                { UnitSymbolType.UST_DEGREE_R_DIFFERENCE, "°R" },
                { UnitSymbolType.UST_DELTA_DEGREE_R, "delta°R" },
            };
        }

        /// <summary>
        /// Tries to get the symbol for the given <see cref="UnitSymbolType"/> value.
        /// </summary>
        /// <param name="unitSymbol">The unit symbol.</param>
        /// <param name="unitSymbolString">The unit symbol string representation.</param>
        /// <returns></returns>
        public static bool TryGetSymbol(this UnitSymbolType unitSymbol, out string unitSymbolString)
        {
            return unitSymbolTypes.TryGetValue(unitSymbol, out unitSymbolString);
        }

        /// <summary>
        /// Tries to get from symbol.
        /// </summary>
        /// <param name="unitSymbolString">The unit symbol string.</param>
        /// <param name="unitSymbol">The unit symbol.</param>
        /// <returns></returns>
        public static bool TryGetFromSymbol(this string unitSymbolString, out UnitSymbolType unitSymbol)
        {
            var valueExists = unitSymbolTypes.ContainsValue(unitSymbolString);
            unitSymbol = (!valueExists)
                ? UnitSymbolType.UST_NONE
                : unitSymbolTypes
                        .FirstOrDefault(x => x.Value.Equals(unitSymbolString, StringComparison.OrdinalIgnoreCase))
                        .Key;

            return valueExists;
        }
    }
}
