// ReSharper disable InconsistentNaming

using System.Collections.Generic;

namespace CodeCave.Revit.Toolkit
{
    /// <summary> A list of all the built in categories within Revit. </summary>
    // Decompiled with JetBrains decompiler
    // Type: Autodesk.Revit.DB.BuiltInCategory
    // Assembly: RevitAPI, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null
    // MVID: EBF12551-D525-4A0A-8686-7022E5DC12EE
    // Missing XML comment for publicly visible type or member
#pragma warning disable CS1591
    public enum BuiltInCategory
    {
        OST_StackedWalls_Obsolete_IdInWrongRange = -20034100,
        OST_MassTags_Obsolete_IdInWrongRange = -20034005,
        OST_MassSurface_Obsolete_IdInWrongRange = -20034004,
        OST_MassFloor_Obsolete_IdInWrongRange = -20034003,
        OST_Mass_Obsolete_IdInWrongRange = -20034000,
        OST_WallRefPlanes_Obsolete_IdInWrongRange = -20000896,
        OST_StickSymbols_Obsolete_IdInWrongRange = -20000828,
        OST_RemovedGridSeg_Obsolete_IdInWrongRange = -20000827,
        OST_PointClouds = -2010001,
        OST_AssemblyOrigin_Lines = -2009661,
        OST_AssemblyOrigin_Planes = -2009660,
        OST_AssemblyOrigin_Points = -2009659,
        OST_AssemblyOrigin = -2009658,
        OST_LinksAnalytical = -2009657,
        OST_FoundationSlabAnalyticalTags = -2009656,
        OST_WallFoundationAnalyticalTags = -2009655,
        OST_IsolatedFoundationAnalyticalTags = -2009654,
        OST_WallAnalyticalTags = -2009653,
        OST_FloorAnalyticalTags = -2009652,
        OST_ColumnAnalyticalTags = -2009651,
        OST_BraceAnalyticalTags = -2009650,
        OST_BeamAnalyticalTags = -2009649,
        OST_AnalyticalNodes_Lines = -2009648,
        OST_AnalyticalNodes_Planes = -2009647,
        OST_AnalyticalNodes_Points = -2009646,
        OST_AnalyticalNodes = -2009645,
        OST_RigidLinksAnalytical = -2009644,
        OST_FoundationSlabAnalytical = -2009643,
        OST_WallFoundationAnalytical = -2009642,
        OST_IsolatedFoundationAnalytical = -2009641,
        OST_WallAnalytical = -2009640,
        OST_FloorAnalytical = -2009639,
        OST_ColumnEndSegment = -2009638,
        OST_ColumnStartSegment = -2009637,
        OST_ColumnAnalytical = -2009636,
        OST_BraceEndSegment = -2009635,
        OST_BraceStartSegment = -2009634,
        OST_BraceAnalytical = -2009633,
        OST_BeamEndSegment = -2009632,
        OST_BeamStartSegment = -2009631,
        OST_BeamAnalytical = -2009630,
        OST_CompassSecondaryMonth = -2009624,
        OST_CompassPrimaryMonth = -2009623,
        OST_CompassSectionFilled = -2009622,
        OST_LightLine = -2009621,
        OST_MultiSurface = -2009620,
        OST_SunSurface = -2009619,
        OST_Analemma = -2009618,
        OST_SunsetText = -2009617,
        OST_CompassSection = -2009616,
        OST_CompassOuter = -2009615,
        OST_SunriseText = -2009614,
        OST_CompassInner = -2009613,
        OST_SunPath2 = -2009612,
        OST_SunPath1 = -2009611,
        OST_Sun = -2009610,
        OST_SunStudy = -2009609,
        OST_StructuralTrussStickSymbols = -2009608,
        OST_StructuralTrussHiddenLines = -2009607,
        OST_TrussChord = -2009606,
        OST_TrussWeb = -2009605,
        OST_TrussBottomChordCurve = -2009604,
        OST_TrussTopChordCurve = -2009603,
        OST_TrussVertWebCurve = -2009602,
        OST_TrussDiagWebCurve = -2009601,
        OST_Truss = -2009600,
        OST_RailingSystemTransitionHiddenLines_Deprecated = -2009549,
        OST_RailingSystemTerminationHiddenLines_Deprecated = -2009548,
        OST_RailingSystemRailHiddenLines_Deprecated = -2009547,
        OST_RailingSystemTopRailHiddenLines_Deprecated = -2009546,
        OST_RailingSystemHandRailBracketHiddenLines_Deprecated = -2009545,
        OST_RailingSystemHandRailHiddenLines_Deprecated = -2009544,
        OST_RailingSystemPanelBracketHiddenLines_Deprecated = -2009543,
        OST_RailingSystemPanelHiddenLines_Deprecated = -2009542,
        OST_RailingSystemBalusterHiddenLines_Deprecated = -2009541,
        OST_RailingSystemPostHiddenLines_Deprecated = -2009540,
        OST_RailingSystemSegmentHiddenLines_Deprecated = -2009539,
        OST_RailingSystemHiddenLines_Deprecated = -2009538,
        OST_StairStringer2012HiddenLines_Deprecated = -2009537,
        OST_StairTread2012HiddenLines_Deprecated = -2009536,
        OST_StairLanding2012HiddenLines_Deprecated = -2009535,
        OST_StairRun2012HiddenLines_Deprecated = -2009534,
        OST_Stairs2012HiddenLines_Deprecated = -2009533,
        OST_MassHiddenLines = -2009532,
        OST_CurtaSystemHiddenLines = -2009531,
        OST_OBSOLETE_ElemArrayHiddenLines = -2009530,
        OST_EntourageHiddenLines = -2009529,
        OST_PlantingHiddenLines = -2009528,
        OST_SpecialityEquipmentHiddenLines = -2009527,
        OST_TopographyHiddenLines = -2009526,
        OST_StructuralFramingSystemHiddenLines_Obsolete = -2009525,
        OST_SiteHiddenLines = -2009524,
        OST_RoadsHiddenLines = -2009523,
        OST_ParkingHiddenLines = -2009522,
        OST_PlumbingFixturesHiddenLines = -2009521,
        OST_MechanicalEquipmentHiddenLines = -2009520,
        OST_LightingFixturesHiddenLines = -2009519,
        OST_FurnitureSystemsHiddenLines = -2009518,
        OST_ElectricalFixturesHiddenLines = -2009517,
        OST_ElectricalEquipmentHiddenLines = -2009516,
        OST_CaseworkHiddenLines = -2009515,
        OST_DetailComponentsHiddenLines = -2009514,
        OST_ShaftOpeningHiddenLines = -2009513,
        OST_GenericModelHiddenLines = -2009512,
        OST_CurtainWallMullionsHiddenLines = -2009511,
        OST_CurtainWallPanelsHiddenLines = -2009510,
        OST_RampsHiddenLines = -2009509,
        OST_StairsRailingHiddenLines = -2009508,
        OST_StairsHiddenLines = -2009507,
        OST_ColumnsHiddenLines = -2009506,
        OST_FurnitureHiddenLines = -2009505,
        OST_LinesHiddenLines = -2009504,
        OST_CeilingsHiddenLines = -2009503,
        OST_RoofsHiddenLines = -2009502,
        OST_DoorsHiddenLines = -2009501,
        OST_WindowsHiddenLines = -2009500,
        OST_CouplerHiddenLines = -2009062,
        OST_CouplerTags = -2009061,
        OST_Coupler = -2009060,
        OST_RebarHiddenLines = -2009050,
        OST_StructConnectionOthers = -2009042,
        OST_StructConnectionBolts = -2009041,
        OST_StructConnectionTags = -2009040,
        OST_StructConnectionAnchors = -2009039,
        OST_StructConnectionPlates = -2009038,
        OST_StructConnectionProfiles = -2009037,
        OST_StructConnectionReference = -2009036,
        OST_StructConnectionFailed = -2009035,
        OST_StructConnectionStale = -2009034,
        OST_StructConnectionSymbol = -2009033,
        OST_StructConnectionHiddenLines = -2009032,
        OST_StructWeldLines = -2009031,
        OST_StructConnections = -2009030,
        OST_FabricAreaBoundary = -2009029,
        OST_FabricReinSpanSymbol = -2009028,
        OST_FabricReinforcementWire = -2009027,
        OST_FabricReinforcementBoundary = -2009026,
        OST_RebarSetToggle = -2009025,
        OST_FabricAreaTags = -2009023,
        OST_FabricReinforcementTags = -2009022,
        OST_AreaReinTags = -2009021,
        OST_RebarTags = -2009020,
        OST_FabricAreaSketchSheetsLines = -2009019,
        OST_FabricAreaSketchEnvelopeLines = -2009018,
        OST_FabricAreas = -2009017,
        OST_FabricReinforcement = -2009016,
        OST_RebarCover = -2009015,
        OST_CoverType = -2009014,
        OST_RebarShape = -2009013,
        OST_PathReinBoundary = -2009012,
        OST_PathReinTags = -2009011,
        OST_PathReinSpanSymbol = -2009010,
        OST_PathRein = -2009009,
        OST_Cage = -2009008,
        OST_AreaReinXVisibility = -2009007,
        OST_AreaReinBoundary = -2009006,
        OST_AreaReinSpanSymbol = -2009005,
        OST_AreaReinSketchOverride = -2009004,
        OST_AreaRein = -2009003,
        OST_RebarLines = -2009002,
        OST_RebarSketchLines = -2009001,
        OST_Rebar = -2009000,
        OST_FabricationPipeworkInsulation = -2008221,
        OST_FabricationDuctworkLining = -2008220,
        OST_FabricationContainmentDrop = -2008219,
        OST_FabricationContainmentRise = -2008218,
        OST_FabricationPipeworkDrop = -2008217,
        OST_FabricationPipeworkRise = -2008216,
        OST_FabricationContainmentSymbology = -2008215,
        OST_FabricationContainmentCenterLine = -2008214,
        OST_FabricationContainmentTags = -2008213,
        OST_FabricationContainment = -2008212,
        OST_FabricationPipeworkSymbology = -2008211,
        OST_FabricationPipeworkCenterLine = -2008210,
        OST_FabricationPipeworkTags = -2008209,
        OST_FabricationPipework = -2008208,
        OST_FabricationDuctworkSymbology = -2008207,
        OST_FabricationDuctworkDrop = -2008206,
        OST_FabricationDuctworkRise = -2008205,
        OST_FabricationHangerTags = -2008204,
        OST_FabricationHangers = -2008203,
        OST_OBSOLETE_FabricationPartsTmpGraphicDropDrag = -2008202,
        OST_FabricationPartsTmpGraphicDrag = -2008201,
        OST_OBSOLETE_FabricationPartsTmpGraphicDrop = -2008200,
        OST_FabricationPartsTmpGraphicEnd = -2008199,
        OST_FabricationDuctworkInsulation = -2008198,
        OST_LayoutNodes = -2008197,
        OST_FabricationDuctworkCenterLine = -2008196,
        OST_FabricationServiceElements = -2008195,
        OST_FabricationDuctworkTags = -2008194,
        OST_FabricationDuctwork = -2008193,
        OST_LayoutPathBase_Pipings = -2008192,
        OST_NumberingSchemas = -2008191,
        OST_DivisionRules = -2008190,
        OST_gbXML_Shade = -2008187,
        OST_AnalyticSurfaces = -2008186,
        OST_AnalyticSpaces = -2008185,
        OST_gbXML_OpeningAir = -2008184,
        OST_gbXML_NonSlidingDoor = -2008183,
        OST_gbXML_SlidingDoor = -2008182,
        OST_gbXML_OperableSkylight = -2008181,
        OST_gbXML_FixedSkylight = -2008180,
        OST_gbXML_OperableWindow = -2008179,
        OST_gbXML_FixedWindow = -2008178,
        OST_gbXML_UndergroundCeiling = -2008177,
        OST_gbXML_UndergroundSlab = -2008176,
        OST_gbXML_UndergroundWall = -2008175,
        OST_gbXML_SurfaceAir = -2008174,
        OST_gbXML_Ceiling = -2008173,
        OST_gbXML_InteriorFloor = -2008172,
        OST_gbXML_InteriorWall = -2008171,
        OST_gbXML_SlabOnGrade = -2008170,
        OST_gbXML_RaisedFloor = -2008169,
        OST_gbXML_Roof = -2008168,
        OST_gbXML_ExteriorWall = -2008167,
        OST_DivisionProfile = -2008165,
        OST_SplitterProfile = -2008164,
        OST_PipeSegments = -2008163,
        OST_GraphicalWarning_OpenConnector = -2008162,
        OST_PlaceHolderPipes = -2008161,
        OST_PlaceHolderDucts = -2008160,
        OST_PipingSystem_Reference_Visibility = -2008159,
        OST_PipingSystem_Reference = -2008158,
        OST_DuctSystem_Reference_Visibility = -2008157,
        OST_DuctSystem_Reference = -2008156,
        OST_PipeInsulationsTags = -2008155,
        OST_DuctLiningsTags = -2008154,
        OST_DuctInsulationsTags = -2008153,
        OST_ElectricalInternalCircuits = -2008152,
        OST_PanelScheduleGraphics = -2008151,
        OST_CableTrayRun = -2008150,
        OST_ConduitRun = -2008149,
        OST_ParamElemElectricalLoadClassification = -2008148,
        OST_DataPanelScheduleTemplates = -2008147,
        OST_SwitchboardScheduleTemplates = -2008146,
        OST_BranchPanelScheduleTemplates = -2008145,
        OST_ConduitStandards = -2008144,
        OST_ElectricalLoadClassifications = -2008143,
        OST_ElectricalDemandFactorDefinitions = -2008142,
        OST_ConduitFittingCenterLine = -2008141,
        OST_CableTrayFittingCenterLine = -2008140,
        OST_ConduitCenterLine = -2008139,
        OST_ConduitDrop = -2008138,
        OST_ConduitRiseDrop = -2008137,
        OST_CableTrayCenterLine = -2008136,
        OST_CableTrayDrop = -2008135,
        OST_CableTrayRiseDrop = -2008134,
        OST_ConduitTags = -2008133,
        OST_Conduit = -2008132,
        OST_CableTrayTags = -2008131,
        OST_CableTray = -2008130,
        OST_ConduitFittingTags = -2008129,
        OST_ConduitFitting = -2008128,
        OST_CableTrayFittingTags = -2008127,
        OST_CableTrayFitting = -2008126,
        OST_RoutingPreferences = -2008125,
        OST_DuctLinings = -2008124,
        OST_DuctInsulations = -2008123,
        OST_PipeInsulations = -2008122,
        OST_HVAC_Load_Schedules = -2008121,
        OST_HVAC_Load_Building_Types = -2008120,
        OST_HVAC_Load_Space_Types = -2008119,
        OST_HVAC_Zones_Reference_Visibility = -2008118,
        OST_HVAC_Zones_InteriorFill_Visibility = -2008117,
        OST_HVAC_Zones_ColorFill = -2008116,
        OST_ZoneTags = -2008115,
        OST_LayoutPath_Bases = -2008114,
        OST_WireTemperatureRatings = -2008113,
        OST_WireInsulations = -2008112,
        OST_WireMaterials = -2008111,
        OST_HVAC_Zones_Reference = -2008110,
        OST_HVAC_Zones_InteriorFill = -2008109,
        OST_HVAC_Zones_Boundary = -2008108,
        OST_HVAC_Zones = -2008107,
        OST_Fluids = -2008106,
        OST_PipeSchedules = -2008105,
        OST_PipeMaterials = -2008104,
        OST_PipeConnections = -2008103,
        OST_EAConstructions = -2008102,
        OST_SwitchSystem = -2008101,
        OST_SprinklerTags = -2008100,
        OST_Sprinklers = -2008099,
        OST_RouteCurveBranch = -2008098,
        OST_RouteCurveMain = -2008097,
        OST_RouteCurve = -2008096,
        OST_GbXML_Opening = -2008095,
        OST_GbXML_SType_Underground = -2008094,
        OST_GbXML_SType_Shade = -2008093,
        OST_GbXML_SType_Exterior = -2008092,
        OST_GbXML_SType_Interior = -2008091,
        OST_GbXMLFaces = -2008090,
        OST_WireHomeRunArrows = -2008089,
        OST_LightingDeviceTags = -2008088,
        OST_LightingDevices = -2008087,
        OST_FireAlarmDeviceTags = -2008086,
        OST_FireAlarmDevices = -2008085,
        OST_DataDeviceTags = -2008084,
        OST_DataDevices = -2008083,
        OST_CommunicationDeviceTags = -2008082,
        OST_CommunicationDevices = -2008081,
        OST_SecurityDeviceTags = -2008080,
        OST_SecurityDevices = -2008079,
        OST_NurseCallDeviceTags = -2008078,
        OST_NurseCallDevices = -2008077,
        OST_TelephoneDeviceTags = -2008076,
        OST_TelephoneDevices = -2008075,
        OST_WireTickMarks = -2008074,
        OST_PipeFittingInsulation = -2008073,
        OST_PipeFittingCenterLine = -2008072,
        OST_FlexPipeCurvesInsulation = -2008071,
        OST_PipeCurvesInsulation = -2008070,
        OST_PipeCurvesDrop = -2008069,
        OST_DuctFittingLining = -2008068,
        OST_DuctFittingInsulation = -2008067,
        OST_DuctFittingCenterLine = -2008066,
        OST_FlexDuctCurvesInsulation = -2008065,
        OST_DuctCurvesLining = -2008064,
        OST_DuctCurvesInsulation = -2008063,
        OST_DuctCurvesDrop = -2008062,
        OST_DuctFittingTags = -2008061,
        OST_PipeFittingTags = -2008060,
        OST_PipeColorFills = -2008059,
        OST_PipeColorFillLegends = -2008058,
        OST_WireTags = -2008057,
        OST_PipeAccessoryTags = -2008056,
        OST_PipeAccessory = -2008055,
        OST_PipeCurvesRiseDrop = -2008054,
        OST_FlexPipeCurvesPattern = -2008053,
        OST_FlexPipeCurvesContour = -2008052,
        OST_FlexPipeCurvesCenterLine = -2008051,
        OST_FlexPipeCurves = -2008050,
        OST_PipeFitting = -2008049,
        OST_FlexPipeTags = -2008048,
        OST_PipeTags = -2008047,
        OST_PipeCurvesContour = -2008046,
        OST_PipeCurvesCenterLine = -2008045,
        OST_PipeCurves = -2008044,
        OST_PipingSystem = -2008043,
        OST_ElectricalDemandFactor = -2008042,
        OST_ElecDistributionSys = -2008041,
        OST_ElectricalVoltage = -2008040,
        OST_Wire = -2008039,
        OST_ElectricalCircuitTags = -2008038,
        OST_ElectricalCircuit = -2008037,
        OST_DuctCurvesRiseDrop = -2008036,
        OST_FlexDuctCurvesPattern = -2008023,
        OST_FlexDuctCurvesContour = -2008022,
        OST_FlexDuctCurvesCenterLine = -2008021,
        OST_FlexDuctCurves = -2008020,
        OST_DuctAccessoryTags = -2008017,
        OST_DuctAccessory = -2008016,
        OST_DuctSystem = -2008015,
        OST_DuctTerminalTags = -2008014,
        OST_DuctTerminal = -2008013,
        OST_DuctFitting = -2008010,
        OST_DuctColorFills = -2008005,
        OST_FlexDuctTags = -2008004,
        OST_DuctTags = -2008003,
        OST_DuctCurvesContour = -2008002,
        OST_DuctCurvesCenterLine = -2008001,
        OST_DuctCurves = -2008000,
        OST_DuctColorFillLegends = -2007004,
        OST_ConnectorElemZAxis = -2007003,
        OST_ConnectorElemYAxis = -2007002,
        OST_ConnectorElemXAxis = -2007001,
        OST_ConnectorElem = -2007000,
        OST_DesignOptions = -2006114,
        OST_DesignOptionSets = -2006112,
        OST_StructuralBracePlanReps = -2006110,
        OST_StructConnectionSymbols = -2006100,
        OST_StructuralAnnotations = -2006090,
        OST_RevisionCloudTags = -2006080,
        OST_Revisions = -2006070,
        OST_RevisionClouds = -2006060,
        OST_EditCutProfile = -2006050,
        OST_ElevationMarks = -2006045,
        OST_GridHeads = -2006040,
        OST_LevelHeads = -2006020,
        OST_DecalType = -2006002,
        OST_DecalElement = -2006001,
        OST_VolumeOfInterest = -2006000,
        OST_BoundaryConditions = -2005301,
        OST_InternalAreaLoadTags = -2005255,
        OST_InternalLineLoadTags = -2005254,
        OST_InternalPointLoadTags = -2005253,
        OST_AreaLoadTags = -2005252,
        OST_LineLoadTags = -2005251,
        OST_PointLoadTags = -2005250,
        OST_LoadCasesSeismic = -2005218,
        OST_LoadCasesTemperature = -2005217,
        OST_LoadCasesAccidental = -2005216,
        OST_LoadCasesRoofLive = -2005215,
        OST_LoadCasesSnow = -2005214,
        OST_LoadCasesWind = -2005213,
        OST_LoadCasesLive = -2005212,
        OST_LoadCasesDead = -2005211,
        OST_LoadCases = -2005210,
        OST_InternalAreaLoads = -2005207,
        OST_InternalLineLoads = -2005206,
        OST_InternalPointLoads = -2005205,
        OST_InternalLoads = -2005204,
        OST_AreaLoads = -2005203,
        OST_LineLoads = -2005202,
        OST_PointLoads = -2005201,
        OST_Loads = -2005200,
        OST_BeamSystemTags = -2005130,
        OST_FootingSpanDirectionSymbol = -2005111,
        OST_SpanDirectionSymbol = -2005110,
        OST_SpotSlopesSymbols = -2005102,
        OST_SpotCoordinateSymbols = -2005101,
        OST_SpotElevSymbols = -2005100,
        OST_StructuralConnectionHandlerTags_Deprecated = -2005031,
        OST_TrussTags = -2005030,
        OST_KeynoteTags = -2005029,
        OST_DetailComponentTags = -2005028,
        OST_MaterialTags = -2005027,
        OST_FloorTags = -2005026,
        OST_CurtaSystemTags = -2005025,
        OST_HostFinTags = -2005024,
        OST_StairsTags = -2005023,
        OST_MultiCategoryTags = -2005022,
        OST_PlantingTags = -2005021,
        OST_AreaTags = -2005020,
        OST_StructuralFoundationTags = -2005019,
        OST_StructuralColumnTags = -2005018,
        OST_ParkingTags = -2005017,
        OST_SiteTags = -2005016,
        OST_StructuralFramingTags = -2005015,
        OST_SpecialityEquipmentTags = -2005014,
        OST_GenericModelTags = -2005013,
        OST_CurtainWallPanelTags = -2005012,
        OST_WallTags = -2005011,
        OST_PlumbingFixtureTags = -2005010,
        OST_MechanicalEquipmentTags = -2005009,
        OST_LightingFixtureTags = -2005008,
        OST_FurnitureSystemTags = -2005007,
        OST_FurnitureTags = -2005006,
        OST_ElectricalFixtureTags = -2005004,
        OST_ElectricalEquipmentTags = -2005003,
        OST_CeilingTags = -2005002,
        OST_CaseworkTags = -2005001,
        OST_Tags = -2005000,
        OST_MEPSpaceColorFill = -2003605,
        OST_MEPSpaceReference = -2003604,
        OST_MEPSpaceInteriorFill = -2003603,
        OST_MEPSpaceReferenceVisibility = -2003602,
        OST_MEPSpaceInteriorFillVisibility = -2003601,
        OST_MEPSpaces = -2003600,
        OST_StackedWalls = -2003500,
        OST_MassGlazingAll = -2003423,
        OST_MassFloorsAll = -2003422,
        OST_MassWallsAll = -2003421,
        OST_MassExteriorWallUnderground = -2003420,
        OST_MassSlab = -2003419,
        OST_MassShade = -2003418,
        OST_MassOpening = -2003417,
        OST_MassSkylights = -2003416,
        OST_MassGlazing = -2003415,
        OST_MassRoof = -2003414,
        OST_MassExteriorWall = -2003413,
        OST_MassInteriorWall = -2003412,
        OST_MassZone = -2003411,
        OST_MassAreaFaceTags = -2003410,
        OST_HostTemplate = -2003409,
        OST_MassFaceSplitter = -2003408,
        OST_MassCutter = -2003407,
        OST_ZoningEnvelope = -2003406,
        OST_MassTags = -2003405,
        OST_MassForm = -2003404,
        OST_MassFloor = -2003403,
        OST_Mass = -2003400,
        OST_DividedSurface_DiscardedDivisionLines = -2003333,
        OST_DividedSurfaceBelt = -2003332,
        OST_TilePatterns = -2003331,
        OST_AlwaysExcludedInAllViews = -2003330,
        OST_DividedSurface_TransparentFace = -2003329,
        OST_DividedSurface_PreDividedSurface = -2003328,
        OST_DividedSurface_PatternFill = -2003327,
        OST_DividedSurface_PatternLines = -2003326,
        OST_DividedSurface_Gridlines = -2003325,
        OST_DividedSurface_Nodes = -2003324,
        OST_DividedSurface = -2003323,
        OST_RepeatingDetailLines = -2003321,
        OST_RampsDownArrow = -2003308,
        OST_RampsUpArrow = -2003307,
        OST_RampsDownText = -2003306,
        OST_RampsUpText = -2003305,
        OST_RampsStringerAboveCut = -2003304,
        OST_RampsStringer = -2003303,
        OST_RampsAboveCut = -2003302,
        OST_RampsIncomplete = -2003301,
        OST_TrussDummy = -2003300,
        OST_ZoneSchemes = -2003225,
        OST_AreaSchemes = -2003201,
        OST_Areas = -2003200,
        OST_ProjectInformation = -2003101,
        OST_Sheets = -2003100,
        OST_ProfileFamilies = -2003000,
        OST_DetailComponents = -2002000,
        OST_RoofSoffit = -2001393,
        OST_EdgeSlab = -2001392,
        OST_Gutter = -2001391,
        OST_Fascia = -2001390,
        OST_Entourage = -2001370,
        OST_Planting = -2001360,
        OST_Blocks = -2001359,
        OST_StructuralStiffenerHiddenLines = -2001358,
        OST_StructuralColumnLocationLine = -2001357,
        OST_StructuralFramingLocationLine = -2001356,
        OST_StructuralStiffenerTags = -2001355,
        OST_StructuralStiffener = -2001354,
        OST_FootingAnalyticalGeometry = -2001353,
        OST_RvtLinks = -2001352,
        OST_Automatic = -2001351,
        OST_SpecialityEquipment = -2001350,
        OST_ColumnAnalyticalRigidLinks = -2001344,
        OST_SecondaryTopographyContours = -2001343,
        OST_TopographyContours = -2001342,
        OST_TopographySurface = -2001341,
        OST_Topography = -2001340,
        OST_StructuralTruss = -2001336,
        OST_StructuralColumnStickSymbols = -2001335,
        OST_HiddenStructuralColumnLines = -2001334,
        OST_AnalyticalRigidLinks = -2001333,
        OST_ColumnAnalyticalGeometry = -2001332,
        OST_FramingAnalyticalGeometry = -2001331,
        OST_StructuralColumns = -2001330,
        OST_HiddenStructuralFramingLines = -2001329,
        OST_KickerBracing = -2001328,
        OST_StructuralFramingSystem = -2001327,
        OST_VerticalBracing = -2001326,
        OST_HorizontalBracing = -2001325,
        OST_Purlin = -2001324,
        OST_Joist = -2001323,
        OST_Girder = -2001322,
        OST_StructuralFramingOther = -2001321,
        OST_StructuralFraming = -2001320,
        OST_HiddenStructuralFoundationLines = -2001302,
        OST_StructuralFoundation = -2001300,
        OST_BasePointAxisZ = -2001275,
        OST_BasePointAxisY = -2001274,
        OST_BasePointAxisX = -2001273,
        OST_SharedBasePoint = -2001272,
        OST_ProjectBasePoint = -2001271,
        OST_SiteRegion = -2001270,
        OST_SitePropertyLineSegmentTags = -2001269,
        OST_SitePropertyLineSegment = -2001268,
        OST_SitePropertyTags = -2001267,
        OST_SitePointBoundary = -2001266,
        OST_SiteProperty = -2001265,
        OST_BuildingPad = -2001263,
        OST_SitePoint = -2001262,
        OST_SiteSurface = -2001261,
        OST_Site = -2001260,
        OST_Sewer = -2001240,
        OST_Roads = -2001220,
        OST_Property = -2001200,
        OST_Parking = -2001180,
        OST_PlumbingFixtures = -2001160,
        OST_MechanicalEquipment = -2001140,
        OST_LightingFixtureSource = -2001121,
        OST_LightingFixtures = -2001120,
        OST_FurnitureSystems = -2001100,
        OST_ElectricalFixtures = -2001060,
        OST_ElectricalEquipment = -2001040,
        OST_Casework = -2001000,
        OST_ArcWallRectOpening = -2000999,
        OST_DormerOpeningIncomplete = -2000998,
        OST_SWallRectOpening = -2000997,
        OST_ShaftOpening = -2000996,
        OST_StructuralFramingOpening = -2000995,
        OST_ColumnOpening = -2000994,
        OST_MultistoryStairs = -2000980,
        OST_HiddenStructuralConnectionLines_Deprecated = -2000979,
        OST_StructuralConnectionHandler_Deprecated = -2000978,
        OST_CoordinateSystem = -2000977,
        OST_FndSlabLocalCoordSys = -2000976,
        OST_FloorLocalCoordSys = -2000975,
        OST_WallLocalCoordSys = -2000974,
        OST_BraceLocalCoordSys = -2000973,
        OST_ColumnLocalCoordSys = -2000972,
        OST_BeamLocalCoordSys = -2000971,
        OST_MultiReferenceAnnotations = -2000970,
        OST_DSR_LeaderTickMarkStyleId = -2000969,
        OST_DSR_InteriorTickMarkStyleId = -2000968,
        OST_DSR_ArrowHeadStyleId = -2000967,
        OST_DSR_CenterlineTickMarkStyleId = -2000966,
        OST_DSR_CenterlinePatternCatId = -2000965,
        OST_DSR_DimStyleHeavyEndCategoryId = -2000964,
        OST_DSR_DimStyleHeavyEndCatId = -2000963,
        OST_DSR_DimStyleTickCategoryId = -2000962,
        OST_DSR_LineAndTextAttrFontId = -2000961,
        OST_DSR_LineAndTextAttrCategoryId = -2000960,
        OST_NodeAnalyticalTags = -2000956,
        OST_LinkAnalyticalTags = -2000955,
        OST_RailingRailPathExtensionLines = -2000954,
        OST_RailingRailPathLines = -2000953,
        OST_StairsSupports = -2000952,
        OST_RailingHandRailAboveCut = -2000951,
        OST_RailingTopRailAboveCut = -2000950,
        OST_RailingTermination = -2000949,
        OST_RailingSupport = -2000948,
        OST_RailingHandRail = -2000947,
        OST_RailingTopRail = -2000946,
        OST_StairsSketchPathLines = -2000945,
        OST_StairsTriserNumbers = -2000944,
        OST_StairsTriserTags = -2000943,
        OST_StairsSupportTags = -2000942,
        OST_StairsLandingTags = -2000941,
        OST_StairsRunTags = -2000940,
        OST_StairsPathsAboveCut = -2000939,
        OST_StairsPaths = -2000938,
        OST_StairsRiserLinesAboveCut = -2000937,
        OST_StairsRiserLines = -2000936,
        OST_StairsOutlinesAboveCut = -2000935,
        OST_StairsOutlines = -2000934,
        OST_StairsNosingLinesAboveCut = -2000933,
        OST_StairsNosingLines = -2000932,
        OST_StairsCutMarksAboveCut = -2000931,
        OST_StairsCutMarks = -2000930,
        OST_ComponentRepeaterSlot = -2000928,
        OST_ComponentRepeater = -2000927,
        OST_DividedPath = -2000926,
        OST_IOSRoomCalculationPoint = -2000925,
        OST_PropertySet = -2000924,
        OST_AppearanceAsset = -2000923,
        OST_StairStringer2012_Deprecated = -2000922,
        OST_StairsTrisers = -2000921,
        OST_StairsLandings = -2000920,
        OST_StairsRuns = -2000919,
        OST_Stair2012_Deprecated = -2000918,
        OST_RailingSystemTags = -2000917,
        OST_RailingSystemTransition = -2000916,
        OST_RailingSystemTermination = -2000915,
        OST_RailingSystemRail = -2000914,
        OST_RailingSystemTopRail = -2000913,
        OST_RailingSystemHandRailBracket = -2000912,
        OST_RailingSystemHandRail = -2000911,
        OST_RailingSystemHardware = -2000910,
        OST_RailingSystemPanel = -2000909,
        OST_RailingSystemBaluster = -2000908,
        OST_RailingSystemPost = -2000907,
        OST_RailingSystemSegment = -2000906,
        OST_RailingSystem = -2000905,
        OST_AdaptivePoints_HiddenLines = -2000904,
        OST_AdaptivePoints_Lines = -2000903,
        OST_AdaptivePoints_Planes = -2000902,
        OST_AdaptivePoints_Points = -2000901,
        OST_AdaptivePoints = -2000900,
        OST_CeilingOpening = -2000899,
        OST_FloorOpening = -2000898,
        OST_RoofOpening = -2000897,
        OST_WallRefPlanes = -2000896,
        OST_StructLocationLineControl = -2000880,
        OST_DimLockControlLeader = -2000832,
        OST_MEPSpaceSeparationLines = -2000831,
        OST_AreaPolylines = -2000830,
        OST_RoomPolylines = -2000829,
        OST_InstanceDrivenLineStyle = -2000828,
        OST_RemovedGridSeg = -2000827,
        OST_IOSOpening = -2000810,
        OST_IOSTilePatternGrid = -2000800,
        OST_ControlLocal = -2000774,
        OST_ControlAxisZ = -2000773,
        OST_ControlAxisY = -2000772,
        OST_ControlAxisX = -2000721,
        OST_XRayConstrainedProfileEdge = -2000720,
        OST_XRayImplicitPathCurve = -2000719,
        OST_XRayPathPoint = -2000718,
        OST_XRayPathCurve = -2000717,
        OST_XRaySideEdge = -2000716,
        OST_XRayProfileEdge = -2000715,
        OST_ReferencePoints_HiddenLines = -2000714,
        OST_ReferencePoints_Lines = -2000713,
        OST_ReferencePoints_Planes = -2000712,
        OST_ReferencePoints_Points = -2000711,
        OST_ReferencePoints = -2000710,
        OST_Materials = -2000700,
        OST_CeilingsCutPattern = -2000617,
        OST_CeilingsDefault = -2000616,
        OST_CeilingsFinish2 = -2000615,
        OST_CeilingsFinish1 = -2000614,
        OST_CeilingsSubstrate = -2000613,
        OST_CeilingsInsulation = -2000612,
        OST_CeilingsStructure = -2000611,
        OST_CeilingsMembrane = -2000610,
        OST_FloorsInteriorEdges = -2000609,
        OST_FloorsCutPattern = -2000608,
        OST_HiddenFloorLines = -2000607,
        OST_FloorsDefault = -2000606,
        OST_FloorsFinish2 = -2000605,
        OST_FloorsFinish1 = -2000604,
        OST_FloorsSubstrate = -2000603,
        OST_FloorsInsulation = -2000602,
        OST_FloorsStructure = -2000601,
        OST_FloorsMembrane = -2000600,
        OST_RoofsInteriorEdges = -2000598,
        OST_RoofsCutPattern = -2000597,
        OST_RoofsDefault = -2000596,
        OST_RoofsFinish2 = -2000595,
        OST_RoofsFinish1 = -2000594,
        OST_RoofsSubstrate = -2000593,
        OST_RoofsInsulation = -2000592,
        OST_RoofsStructure = -2000591,
        OST_RoofsMembrane = -2000590,
        OST_WallsCutPattern = -2000588,
        OST_HiddenWallLines = -2000587,
        OST_WallsDefault = -2000586,
        OST_WallsFinish2 = -2000585,
        OST_WallsFinish1 = -2000584,
        OST_WallsSubstrate = -2000583,
        OST_WallsInsulation = -2000582,
        OST_WallsStructure = -2000581,
        OST_WallsMembrane = -2000580,
        OST_PreviewLegendComponents = -2000576,
        OST_LegendComponents = -2000575,
        OST_ScheduleGraphics = -2000570,
        OST_RasterImages = -2000560,
        OST_ColorFillSchema = -2000552,
        OST_RoomColorFill = -2000551,
        OST_ColorFillLegends = -2000550,
        OST_AnnotationCropSpecial = -2000549,
        OST_CropBoundarySpecial = -2000548,
        OST_AnnotationCrop = -2000547,
        OST_FloorsAnalyticalGeometry = -2000546,
        OST_WallsAnalyticalGeometry = -2000545,
        OST_CalloutLeaderLine = -2000544,
        OST_CeilingsSurfacePattern = -2000543,
        OST_RoofsSurfacePattern = -2000542,
        OST_FloorsSurfacePattern = -2000541,
        OST_WallsSurfacePattern = -2000540,
        OST_CalloutBoundary = -2000539,
        OST_CalloutHeads = -2000538,
        OST_Callouts = -2000537,
        OST_CropBoundary = -2000536,
        OST_Elev = -2000535,
        OST_AxisZ = -2000533,
        OST_AxisY = -2000532,
        OST_AxisX = -2000531,
        OST_CLines = -2000530,
        OST_Lights = -2000520,
        OST_ViewportLabel = -2000515,
        OST_Viewports = -2000510,
        OST_Camera_Lines = -2000501,
        OST_Cameras = -2000500,
        OST_MEPSpaceTags = -2000485,
        OST_RoomTags = -2000480,
        OST_DoorTags = -2000460,
        OST_WindowTags = -2000450,
        OST_SectionHeadWideLines = -2000404,
        OST_SectionHeadMediumLines = -2000403,
        OST_SectionHeadThinLines = -2000401,
        OST_SectionHeads = -2000400,
        OST_ContourLabels = -2000350,
        OST_CurtaSystemFaceManager = -2000341,
        OST_CurtaSystem = -2000340,
        OST_AreaReport_Arc_Minus = -2000328,
        OST_AreaReport_Arc_Plus = -2000327,
        OST_AreaReport_Boundary = -2000326,
        OST_AreaReport_Triangle = -2000325,
        OST_CurtainGridsCurtaSystem = -2000323,
        OST_CurtainGridsSystem = -2000322,
        OST_CurtainGridsWall = -2000321,
        OST_CurtainGridsRoof = -2000320,
        OST_HostFinHF = -2000315,
        OST_HostFinWall = -2000314,
        OST_HostFinCeiling = -2000313,
        OST_HostFinRoof = -2000312,
        OST_HostFinFloor = -2000311,
        OST_HostFin = -2000310,
        OST_AnalysisDisplayStyle = -2000304,
        OST_AnalysisResults = -2000303,
        OST_RenderRegions = -2000302,
        OST_SectionBox = -2000301,
        OST_TextNotes = -2000300,
        OST_Divisions = -2000291,
        OST_Catalogs = -2000290,
        OST_DirectionEdgeLines = -2000289,
        OST_CenterLines = -2000288,
        OST_LinesBeyond = -2000287,
        OST_HiddenLines = -2000286,
        OST_DemolishedLines = -2000285,
        OST_OverheadLines = -2000284,
        OST_TitleBlockWideLines = -2000283,
        OST_TitleBlockMediumLines = -2000282,
        OST_TitleBlockThinLines = -2000281,
        OST_TitleBlocks = -2000280,
        OST_Views = -2000279,
        OST_Viewers = -2000278,
        OST_PartHiddenLines = -2000271,
        OST_PartTags = -2000270,
        OST_Parts = -2000269,
        OST_AssemblyTags = -2000268,
        OST_Assemblies = -2000267,
        OST_RoofTags = -2000266,
        OST_SpotSlopes = -2000265,
        OST_SpotCoordinates = -2000264,
        OST_SpotElevations = -2000263,
        OST_Constraints = -2000262,
        OST_WeakDims = -2000261,
        OST_Dimensions = -2000260,
        OST_Levels = -2000240,
        OST_DisplacementPath = -2000223,
        OST_DisplacementElements = -2000222,
        OST_GridChains = -2000221,
        OST_Grids = -2000220,
        OST_BrokenSectionLine = -2000202,
        OST_SectionLine = -2000201,
        OST_Sections = -2000200,
        OST_ReferenceViewer = -2000198,
        OST_ReferenceViewerSymbol = -2000197,
        OST_ImportObjectStyles = -2000196,
        OST_ModelText = -2000195,
        OST_MaskingRegion = -2000194,
        OST_Matchline = -2000193,
        OST_FaceSplitter = -2000192,
        OST_PlanRegion = -2000191,
        OST_FilledRegion = -2000190,
        OST_MassingProjectionOutlines = -2000187,
        OST_MassingCutOutlines = -2000186,
        OST_Massing = -2000185,
        OST_Reveals = -2000182,
        OST_Cornices = -2000181,
        OST_Ramps = -2000180,
        OST_RailingBalusterRailCut = -2000177,
        OST_RailingBalusterRail = -2000176,
        OST_Railings = -2000175,
        OST_CurtainGrids = -2000173,
        OST_CurtainWallMullionsCut = -2000172,
        OST_CurtainWallMullions = -2000171,
        OST_CurtainWallPanels = -2000170,
        OST_AreaReference = -2000169,
        OST_AreaInteriorFill = -2000168,
        OST_RoomReference = -2000167,
        OST_RoomInteriorFill = -2000166,
        OST_AreaColorFill = -2000165,
        OST_AreaReferenceVisibility = -2000164,
        OST_AreaInteriorFillVisibility = -2000163,
        OST_RoomReferenceVisibility = -2000162,
        OST_RoomInteriorFillVisibility = -2000161,
        OST_Rooms = -2000160,
        OST_GenericModel = -2000151,
        OST_GenericAnnotation = -2000150,
        OST_Fixtures = -2000140,
        OST_StairsRailingTags = -2000133,
        OST_StairsRailingAboveCut = -2000132,
        OST_StairsDownArrows = -2000131,
        OST_StairsUpArrows = -2000130,
        OST_StairsDownText = -2000129,
        OST_StairsRailingRail = -2000128,
        OST_StairsRailingBaluster = -2000127,
        OST_StairsRailing = -2000126,
        OST_StairsUpText = -2000125,
        OST_StairsSupportsAboveCut = -2000124,
        OST_StairsStringerCarriage = -2000123,
        OST_StairsAboveCut_ToBeDeprecated = -2000122,
        OST_StairsIncomplete_Deprecated = -2000121,
        OST_Stairs = -2000120,
        OST_IOSNavWheelPivotBall = -2000117,
        OST_IOSRoomComputationHeight = -2000116,
        OST_IOSRoomUpperLowerLines = -2000115,
        OST_IOSDragBoxInverted = -2000114,
        OST_IOSDragBox = -2000113,
        OST_Phases = -2000112,
        OST_IOS_GeoSite = -2000111,
        OST_IOS_GeoLocations = -2000110,
        OST_IOSFabricReinSpanSymbolCtrl = -2000109,
        OST_GuideGrid = -2000107,
        OST_EPS_Future = -2000106,
        OST_EPS_Temporary = -2000105,
        OST_EPS_New = -2000104,
        OST_EPS_Demolished = -2000103,
        OST_EPS_Existing = -2000102,
        OST_IOSMeasureLineScreenSize = -2000101,
        OST_Columns = -2000100,
        OST_IOSRebarSystemSpanSymbolCtrl = -2000099,
        OST_IOSRoomTagToRoomLines = -2000098,
        OST_IOSAttachedDetailGroups = -2000097,
        OST_IOSDetailGroups = -2000096,
        OST_IOSModelGroups = -2000095,
        OST_IOSSuspendedSketch = -2000094,
        OST_IOSWallCoreBoundary = -2000093,
        OST_IOSMeasureLine = -2000092,
        OST_IOSArrays = -2000091,
        OST_Curtain_Systems = -2000090,
        OST_IOSBBoxScreenSize = -2000089,
        OST_IOSSlabShapeEditorPointInterior = -2000088,
        OST_IOSSlabShapeEditorPointBoundary = -2000087,
        OST_IOSSlabShapeEditorBoundary = -2000086,
        OST_IOSSlabShapeEditorAutoCrease = -2000085,
        OST_IOSSlabShapeEditorExplitCrease = -2000084,
        OST_ReferenceLines = -2000083,
        OST_IOSNotSilhouette = -2000082,
        OST_FillPatterns = -2000081,
        OST_Furniture = -2000080,
        OST_AreaSchemeLines = -2000079,
        OST_GenericLines = -2000078,
        OST_InsulationLines = -2000077,
        OST_CloudLines = -2000076,
        OST_IOSRoomPerimeterLines = -2000075,
        OST_IOSCuttingGeometry = -2000074,
        OST_IOSCrashGraphics = -2000073,
        OST_IOSGroups = -2000072,
        OST_IOSGhost = -2000071,
        OST_StairsSketchLandingCenterLines = -2000070,
        OST_StairsSketchRunLines = -2000069,
        OST_StairsSketchRiserLines = -2000068,
        OST_StairsSketchBoundaryLines = -2000067,
        OST_RoomSeparationLines = -2000066,
        OST_AxisOfRotation = -2000065,
        OST_InvisibleLines = -2000064,
        OST_IOSThinPixel_DashDot = -2000063,
        OST_IOSThinPixel_Dash = -2000062,
        OST_IOSThinPixel_Dot = -2000061,
        OST_Extrusions = -2000060,
        OST_IOS = -2000059,
        OST_CutOutlines = -2000058,
        OST_IOSThinPixel = -2000057,
        OST_IOSFlipControl = -2000056,
        OST_IOSSketchGrid = -2000055,
        OST_IOSSuspendedSketch_obsolete = -2000054,
        OST_IOSFreeSnapLine = -2000053,
        OST_IOSDatumPlane = -2000052,
        OST_Lines = -2000051,
        OST_IOSConstructionLine = -2000050,
        OST_IOSAlignmentGraphics = -2000049,
        OST_IOSAligningLine = -2000048,
        OST_IOSBackedUpElements = -2000047,
        OST_IOSRegeneratedElements = -2000046,
        OST_SketchLines = -2000045,
        OST_CurvesWideLines = -2000044,
        OST_CurvesMediumLines = -2000043,
        OST_CurvesThinLines = -2000042,
        OST_Curves = -2000041,
        OST_CeilingsProjection = -2000040,
        OST_CeilingsCut = -2000039,
        OST_Ceilings = -2000038,
        OST_RoofsProjection = -2000037,
        OST_RoofsCut = -2000036,
        OST_Roofs = -2000035,
        OST_FloorsProjection = -2000034,
        OST_FloorsCut = -2000033,
        OST_Floors = -2000032,
        OST_DoorsGlassProjection = -2000031,
        OST_DoorsGlassCut = -2000030,
        OST_DoorsFrameMullionProjection = -2000029,
        OST_DoorsFrameMullionCut = -2000028,
        OST_DoorsOpeningProjection = -2000027,
        OST_DoorsOpeningCut = -2000026,
        OST_DoorsPanelProjection = -2000025,
        OST_DoorsPanelCut = -2000024,
        OST_Doors = -2000023,
        OST_WindowsOpeningProjection = -2000022,
        OST_WindowsOpeningCut = -2000021,
        OST_WindowsSillHeadProjection = -2000020,
        OST_WindowsSillHeadCut = -2000019,
        OST_WindowsFrameMullionProjection = -2000018,
        OST_WindowsFrameMullionCut = -2000017,
        OST_WindowsGlassProjection = -2000016,
        OST_WindowsGlassCut = -2000015,
        OST_Windows = -2000014,
        OST_WallsProjectionOutlines = -2000013,
        OST_WallsCutOutlines = -2000012,
        OST_Walls = -2000011,
        OST_IOSRegenerationFailure = -2000010,
        OST_ScheduleViewParamGroup = -2000008,
        OST_MatchSiteComponent = -2000007,
        OST_MatchProfile = -2000006,
        OST_MatchDetail = -2000005,
        OST_MatchAnnotation = -2000004,
        OST_MatchModel = -2000003,
        OST_MatchAll = -2000002,
        INVALID = -1,
    }
#pragma warning restore CS1591

    /// <summary>
    /// Extensions for Revit API BuiltInCategory enum
    /// </summary>
    public static class BuiltInCategoryExtensions
    {
        private static readonly Dictionary<BuiltInCategory, string> _knownCategories;

        static BuiltInCategoryExtensions()
        {
            _knownCategories = new Dictionary<BuiltInCategory, string>
            {
                { BuiltInCategory.OST_LinksAnalytical, "Analytical Links" },
                { BuiltInCategory.OST_FoundationSlabAnalyticalTags, "Analytical Slab Foundation Tags" },
                { BuiltInCategory.OST_WallFoundationAnalyticalTags, "Analytical Wall Foundation Tags" },
                { BuiltInCategory.OST_IsolatedFoundationAnalyticalTags, "Analytical Isolated Foundation Tags" },
                { BuiltInCategory.OST_WallAnalyticalTags, "Analytical Wall Tags" },
                { BuiltInCategory.OST_FloorAnalyticalTags, "Analytical Floor Tags" },
                { BuiltInCategory.OST_ColumnAnalyticalTags, "Analytical Column Tags" },
                { BuiltInCategory.OST_BraceAnalyticalTags, "Analytical Brace Tags" },
                { BuiltInCategory.OST_BeamAnalyticalTags, "Analytical Beam Tags" },
                { BuiltInCategory.OST_AnalyticalNodes, "Analytical Nodes" },
                { BuiltInCategory.OST_FoundationSlabAnalytical, "Analytical Foundation Slabs" },
                { BuiltInCategory.OST_WallFoundationAnalytical, "Analytical Wall Foundations" },
                { BuiltInCategory.OST_IsolatedFoundationAnalytical, "Analytical Isolated Foundations" },
                { BuiltInCategory.OST_WallAnalytical, "Analytical Walls" },
                { BuiltInCategory.OST_FloorAnalytical, "Analytical Floors" },
                { BuiltInCategory.OST_ColumnEndSegment, "Top Segment" },
                { BuiltInCategory.OST_ColumnStartSegment, "Base Segment" },
                { BuiltInCategory.OST_ColumnAnalytical, "Analytical Columns" },
                { BuiltInCategory.OST_BraceEndSegment, "End Segment" },
                { BuiltInCategory.OST_BraceStartSegment, "Start Segment" },
                { BuiltInCategory.OST_BraceAnalytical, "Analytical Braces" },
                { BuiltInCategory.OST_BeamEndSegment, "End Segment" },
                { BuiltInCategory.OST_BeamStartSegment, "Start Segment" },
                { BuiltInCategory.OST_BeamAnalytical, "Analytical Beams" },
                { BuiltInCategory.OST_StructuralTrussStickSymbols, "Stick Symbols" },
                { BuiltInCategory.OST_MassHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CurtaSystemHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_EntourageHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_PlantingHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_SpecialityEquipmentHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_TopographyHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_SiteHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_RoadsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ParkingHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_PlumbingFixturesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_MechanicalEquipmentHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_LightingFixturesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_FurnitureSystemsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ElectricalFixturesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ElectricalEquipmentHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CaseworkHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_DetailComponentsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ShaftOpeningHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_GenericModelHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CurtainWallMullionsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CurtainWallPanelsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_RampsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StairsRailingHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StairsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_ColumnsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_FurnitureHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_LinesHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CeilingsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_RoofsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_DoorsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_WindowsHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CouplerHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_CouplerTags, "Structural Rebar Coupler Tags" },
                { BuiltInCategory.OST_Coupler, "Structural Rebar Couplers" },
                { BuiltInCategory.OST_RebarHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructConnectionOthers, "Others" },
                { BuiltInCategory.OST_StructConnectionBolts, "Bolts" },
                { BuiltInCategory.OST_StructConnectionTags, "Structural Connection Tags" },
                { BuiltInCategory.OST_StructConnectionAnchors, "Anchors" },
                { BuiltInCategory.OST_StructConnectionPlates, "Plates" },
                { BuiltInCategory.OST_StructConnectionProfiles, "Profiles" },
                { BuiltInCategory.OST_StructConnectionReference, "Reference" },
                { BuiltInCategory.OST_StructConnectionSymbol, "Symbol" },
                { BuiltInCategory.OST_StructConnectionHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructConnections, "Structural Connections" },
                { BuiltInCategory.OST_FabricAreaBoundary, "Boundary" },
                { BuiltInCategory.OST_FabricReinSpanSymbol, "Structural Fabric Reinforcement Symbols" },
                { BuiltInCategory.OST_FabricReinforcementWire, "Fabric Wire" },
                { BuiltInCategory.OST_FabricReinforcementBoundary, "Boundary" },
                { BuiltInCategory.OST_RebarSetToggle, "Rebar Set Toggle" },
                { BuiltInCategory.OST_FabricReinforcementTags, "Structural Fabric Reinforcement Tags" },
                { BuiltInCategory.OST_AreaReinTags, "Structural Area Reinforcement Tags" },
                { BuiltInCategory.OST_RebarTags, "Structural Rebar Tags" },
                { BuiltInCategory.OST_FabricAreaSketchSheetsLines, "<Fabric Sheets>" },
                { BuiltInCategory.OST_FabricAreaSketchEnvelopeLines, "<Fabric Envelope>" },
                { BuiltInCategory.OST_FabricAreas, "Structural Fabric Areas" },
                { BuiltInCategory.OST_FabricReinforcement, "Structural Fabric Reinforcement" },
                { BuiltInCategory.OST_RebarCover, "Rebar Cover References" },
                { BuiltInCategory.OST_RebarShape, "Rebar Shape" },
                { BuiltInCategory.OST_PathReinBoundary, "Boundary" },
                { BuiltInCategory.OST_PathReinTags, "Structural Path Reinforcement Tags" },
                { BuiltInCategory.OST_PathReinSpanSymbol, "Structural Path Reinforcement Symbols" },
                { BuiltInCategory.OST_PathRein, "Structural Path Reinforcement" },
                { BuiltInCategory.OST_AreaReinBoundary, "Boundary" },
                { BuiltInCategory.OST_AreaReinSpanSymbol, "Structural Area Reinforcement Symbols" },
                { BuiltInCategory.OST_AreaRein, "Structural Area Reinforcement" },
                { BuiltInCategory.OST_Rebar, "Structural Rebar" },
                { BuiltInCategory.OST_FabricationPipeworkInsulation, "Insulation" },
                { BuiltInCategory.OST_FabricationDuctworkLining, "Lining" },
                { BuiltInCategory.OST_FabricationContainmentDrop, "Drop" },
                { BuiltInCategory.OST_FabricationContainmentRise, "Rise" },
                { BuiltInCategory.OST_FabricationPipeworkDrop, "Drop" },
                { BuiltInCategory.OST_FabricationPipeworkRise, "Rise" },
                { BuiltInCategory.OST_FabricationContainmentSymbology, "Symbology" },
                { BuiltInCategory.OST_FabricationContainmentCenterLine, "Center Line" },
                { BuiltInCategory.OST_FabricationContainmentTags, "MEP Fabrication Containment Tags" },
                { BuiltInCategory.OST_FabricationContainment, "MEP Fabrication Containment" },
                { BuiltInCategory.OST_FabricationPipeworkSymbology, "Symbology" },
                { BuiltInCategory.OST_FabricationPipeworkCenterLine, "Center Line" },
                { BuiltInCategory.OST_FabricationPipeworkTags, "MEP Fabrication Pipework Tags" },
                { BuiltInCategory.OST_FabricationPipework, "MEP Fabrication Pipework" },
                { BuiltInCategory.OST_FabricationDuctworkSymbology, "Symbology" },
                { BuiltInCategory.OST_FabricationDuctworkDrop, "Drop" },
                { BuiltInCategory.OST_FabricationDuctworkRise, "Rise" },
                { BuiltInCategory.OST_FabricationHangerTags, "MEP Fabrication Hanger Tags" },
                { BuiltInCategory.OST_FabricationHangers, "MEP Fabrication Hangers" },
                { BuiltInCategory.OST_FabricationDuctworkInsulation, "Insulation" },
                { BuiltInCategory.OST_FabricationDuctworkCenterLine, "Center Line" },
                { BuiltInCategory.OST_FabricationDuctworkTags, "MEP Fabrication Ductwork Tags" },
                { BuiltInCategory.OST_FabricationDuctwork, "MEP Fabrication Ductwork" },
                { BuiltInCategory.OST_gbXML_Shade, "Shades" },
                { BuiltInCategory.OST_AnalyticSurfaces, "Analytical Surfaces" },
                { BuiltInCategory.OST_AnalyticSpaces, "Analytical Spaces" },
                { BuiltInCategory.OST_gbXML_OpeningAir, "Air Openings" },
                { BuiltInCategory.OST_gbXML_NonSlidingDoor, "Non-sliding Doors" },
                { BuiltInCategory.OST_gbXML_SlidingDoor, "Sliding Doors" },
                { BuiltInCategory.OST_gbXML_OperableSkylight, "Operable Skylights" },
                { BuiltInCategory.OST_gbXML_FixedSkylight, "Fixed Skylights" },
                { BuiltInCategory.OST_gbXML_OperableWindow, "Operable Windows" },
                { BuiltInCategory.OST_gbXML_FixedWindow, "Fixed Windows" },
                { BuiltInCategory.OST_gbXML_UndergroundCeiling, "Underground Ceilings" },
                { BuiltInCategory.OST_gbXML_UndergroundSlab, "Underground Slabs" },
                { BuiltInCategory.OST_gbXML_UndergroundWall, "Underground Walls" },
                { BuiltInCategory.OST_gbXML_SurfaceAir, "Air Surfaces" },
                { BuiltInCategory.OST_gbXML_Ceiling, "Ceilings" },
                { BuiltInCategory.OST_gbXML_InteriorFloor, "Interior Floors" },
                { BuiltInCategory.OST_gbXML_InteriorWall, "Interior Walls" },
                { BuiltInCategory.OST_gbXML_SlabOnGrade, "Slabs on Grade" },
                { BuiltInCategory.OST_gbXML_RaisedFloor, "Raised Floors" },
                { BuiltInCategory.OST_gbXML_Roof, "Roofs" },
                { BuiltInCategory.OST_gbXML_ExteriorWall, "Exterior Walls" },
                { BuiltInCategory.OST_PipeSegments, "Pipe Segments" },
                { BuiltInCategory.OST_PlaceHolderPipes, "Pipe Placeholders" },
                { BuiltInCategory.OST_PlaceHolderDucts, "Duct Placeholders" },
                { BuiltInCategory.OST_PipingSystem_Reference_Visibility, "Reference Lines" },
                { BuiltInCategory.OST_DuctSystem_Reference_Visibility, "Reference Lines" },
                { BuiltInCategory.OST_PipeInsulationsTags, "Pipe Insulation Tags" },
                { BuiltInCategory.OST_DuctLiningsTags, "Duct Lining Tags" },
                { BuiltInCategory.OST_DuctInsulationsTags, "Duct Insulation Tags" },
                { BuiltInCategory.OST_ElectricalInternalCircuits, "Electrical Spare/Space Circuits" },
                { BuiltInCategory.OST_PanelScheduleGraphics, "Panel Schedule Graphics" },
                { BuiltInCategory.OST_CableTrayRun, "Cable Tray Runs" },
                { BuiltInCategory.OST_ConduitRun, "Conduit Runs" },
                { BuiltInCategory.OST_ConduitFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_CableTrayFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_ConduitCenterLine, "Center line" },
                { BuiltInCategory.OST_ConduitDrop, "Drop" },
                { BuiltInCategory.OST_ConduitRiseDrop, "Rise" },
                { BuiltInCategory.OST_CableTrayCenterLine, "Center line" },
                { BuiltInCategory.OST_CableTrayDrop, "Drop" },
                { BuiltInCategory.OST_CableTrayRiseDrop, "Rise" },
                { BuiltInCategory.OST_ConduitTags, "Conduit Tags" },
                { BuiltInCategory.OST_Conduit, "Conduits" },
                { BuiltInCategory.OST_CableTrayTags, "Cable Tray Tags" },
                { BuiltInCategory.OST_CableTray, "Cable Trays" },
                { BuiltInCategory.OST_ConduitFittingTags, "Conduit Fitting Tags" },
                { BuiltInCategory.OST_ConduitFitting, "Conduit Fittings" },
                { BuiltInCategory.OST_CableTrayFittingTags, "Cable Tray Fitting Tags" },
                { BuiltInCategory.OST_CableTrayFitting, "Cable Tray Fittings" },
                { BuiltInCategory.OST_RoutingPreferences, "Routing Preferences" },
                { BuiltInCategory.OST_DuctLinings, "Duct Linings" },
                { BuiltInCategory.OST_DuctInsulations, "Duct Insulations" },
                { BuiltInCategory.OST_PipeInsulations, "Pipe Insulations" },
                { BuiltInCategory.OST_HVAC_Zones_Reference_Visibility, "Reference Lines" },
                { BuiltInCategory.OST_HVAC_Zones_InteriorFill_Visibility, "Interior Fill" },
                { BuiltInCategory.OST_HVAC_Zones_ColorFill, "Color Fill" },
                { BuiltInCategory.OST_ZoneTags, "Zone Tags" },
                { BuiltInCategory.OST_HVAC_Zones_Boundary, "Boundary" },
                { BuiltInCategory.OST_HVAC_Zones, "HVAC Zones" },
                { BuiltInCategory.OST_SwitchSystem, "Switch System" },
                { BuiltInCategory.OST_SprinklerTags, "Sprinkler Tags" },
                { BuiltInCategory.OST_Sprinklers, "Sprinklers" },
                { BuiltInCategory.OST_GbXML_Opening, "Opening" },
                { BuiltInCategory.OST_GbXML_SType_Underground, "Underground" },
                { BuiltInCategory.OST_GbXML_SType_Shade, "Shades" },
                { BuiltInCategory.OST_GbXML_SType_Exterior, "Exterior" },
                { BuiltInCategory.OST_GbXML_SType_Interior, "Interior" },
                { BuiltInCategory.OST_GbXMLFaces, "Analytical Surfaces" },
                { BuiltInCategory.OST_WireHomeRunArrows, "Home Run Arrows" },
                { BuiltInCategory.OST_LightingDeviceTags, "Lighting Device Tags" },
                { BuiltInCategory.OST_LightingDevices, "Lighting Devices" },
                { BuiltInCategory.OST_FireAlarmDeviceTags, "Fire Alarm Device Tags" },
                { BuiltInCategory.OST_FireAlarmDevices, "Fire Alarm Devices" },
                { BuiltInCategory.OST_DataDeviceTags, "Data Device Tags" },
                { BuiltInCategory.OST_DataDevices, "Data Devices" },
                { BuiltInCategory.OST_CommunicationDeviceTags, "Communication Device Tags" },
                { BuiltInCategory.OST_CommunicationDevices, "Communication Devices" },
                { BuiltInCategory.OST_SecurityDeviceTags, "Security Device Tags" },
                { BuiltInCategory.OST_SecurityDevices, "Security Devices" },
                { BuiltInCategory.OST_NurseCallDeviceTags, "Nurse Call Device Tags" },
                { BuiltInCategory.OST_NurseCallDevices, "Nurse Call Devices" },
                { BuiltInCategory.OST_TelephoneDeviceTags, "Telephone Device Tags" },
                { BuiltInCategory.OST_TelephoneDevices, "Telephone Devices" },
                { BuiltInCategory.OST_WireTickMarks, "Wire Tick Marks" },
                { BuiltInCategory.OST_PipeFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_PipeCurvesDrop, "Drop" },
                { BuiltInCategory.OST_DuctFittingCenterLine, "Center line" },
                { BuiltInCategory.OST_DuctCurvesDrop, "Drop" },
                { BuiltInCategory.OST_DuctFittingTags, "Duct Fitting Tags" },
                { BuiltInCategory.OST_PipeFittingTags, "Pipe Fitting Tags" },
                { BuiltInCategory.OST_PipeColorFills, "Pipe Color Fill" },
                { BuiltInCategory.OST_PipeColorFillLegends, "Pipe Color Fill Legends" },
                { BuiltInCategory.OST_WireTags, "Wire Tags" },
                { BuiltInCategory.OST_PipeAccessoryTags, "Pipe Accessory Tags" },
                { BuiltInCategory.OST_PipeAccessory, "Pipe Accessories" },
                { BuiltInCategory.OST_PipeCurvesRiseDrop, "Rise" },
                { BuiltInCategory.OST_FlexPipeCurvesPattern, "Pattern" },
                { BuiltInCategory.OST_FlexPipeCurvesCenterLine, "Center Line" },
                { BuiltInCategory.OST_FlexPipeCurves, "Flex Pipes" },
                { BuiltInCategory.OST_PipeFitting, "Pipe Fittings" },
                { BuiltInCategory.OST_FlexPipeTags, "Flex Pipe Tags" },
                { BuiltInCategory.OST_PipeTags, "Pipe Tags" },
                { BuiltInCategory.OST_PipeCurvesCenterLine, "Center Line" },
                { BuiltInCategory.OST_PipeCurves, "Pipes" },
                { BuiltInCategory.OST_PipingSystem, "Piping Systems" },
                { BuiltInCategory.OST_Wire, "Wires" },
                { BuiltInCategory.OST_ElectricalCircuit, "Electrical Circuits" },
                { BuiltInCategory.OST_DuctCurvesRiseDrop, "Rise" },
                { BuiltInCategory.OST_FlexDuctCurvesPattern, "Pattern" },
                { BuiltInCategory.OST_FlexDuctCurvesCenterLine, "Center line" },
                { BuiltInCategory.OST_FlexDuctCurves, "Flex Ducts" },
                { BuiltInCategory.OST_DuctAccessoryTags, "Duct Accessory Tags" },
                { BuiltInCategory.OST_DuctAccessory, "Duct Accessories" },
                { BuiltInCategory.OST_DuctSystem, "Duct Systems" },
                { BuiltInCategory.OST_DuctTerminalTags, "Air Terminal Tags" },
                { BuiltInCategory.OST_DuctTerminal, "Air Terminals" },
                { BuiltInCategory.OST_DuctFitting, "Duct Fittings" },
                { BuiltInCategory.OST_DuctColorFills, "Duct Color Fill" },
                { BuiltInCategory.OST_FlexDuctTags, "Flex Duct Tags" },
                { BuiltInCategory.OST_DuctTags, "Duct Tags" },
                { BuiltInCategory.OST_DuctCurvesCenterLine, "Center line" },
                { BuiltInCategory.OST_DuctCurves, "Ducts" },
                { BuiltInCategory.OST_DuctColorFillLegends, "Duct Color Fill Legends" },
                { BuiltInCategory.OST_StructuralBracePlanReps, "Brace in Plan View Symbols" },
                { BuiltInCategory.OST_StructConnectionSymbols, "Connection Symbols" },
                { BuiltInCategory.OST_StructuralAnnotations, "Structural Annotations" },
                { BuiltInCategory.OST_RevisionCloudTags, "Revision Cloud Tags" },
                { BuiltInCategory.OST_RevisionClouds, "Revision Clouds" },
                { BuiltInCategory.OST_ElevationMarks, "Elevation Marks" },
                { BuiltInCategory.OST_GridHeads, "Grid Heads" },
                { BuiltInCategory.OST_LevelHeads, "Level Heads" },
                { BuiltInCategory.OST_VolumeOfInterest, "Scope Boxes" },
                { BuiltInCategory.OST_BoundaryConditions, "Boundary Conditions" },
                { BuiltInCategory.OST_InternalAreaLoadTags, "Internal Area Load Tags" },
                { BuiltInCategory.OST_InternalLineLoadTags, "Internal Line Load Tags" },
                { BuiltInCategory.OST_InternalPointLoadTags, "Internal Point Load Tags" },
                { BuiltInCategory.OST_AreaLoadTags, "Area Load Tags" },
                { BuiltInCategory.OST_LineLoadTags, "Line Load Tags" },
                { BuiltInCategory.OST_PointLoadTags, "Point Load Tags" },
                { BuiltInCategory.OST_LoadCasesSeismic, "Seismic Loads" },
                { BuiltInCategory.OST_LoadCasesTemperature, "Temperature Loads" },
                { BuiltInCategory.OST_LoadCasesAccidental, "Accidental Loads" },
                { BuiltInCategory.OST_LoadCasesRoofLive, "Roof Live Loads" },
                { BuiltInCategory.OST_LoadCasesSnow, "Snow Loads" },
                { BuiltInCategory.OST_LoadCasesWind, "Wind Loads" },
                { BuiltInCategory.OST_LoadCasesLive, "Live Loads" },
                { BuiltInCategory.OST_LoadCasesDead, "Dead Loads" },
                { BuiltInCategory.OST_LoadCases, "Structural Load Cases" },
                { BuiltInCategory.OST_InternalAreaLoads, "Internal Area Loads" },
                { BuiltInCategory.OST_InternalLineLoads, "Internal Line Loads" },
                { BuiltInCategory.OST_InternalPointLoads, "Internal Point Loads" },
                { BuiltInCategory.OST_InternalLoads, "Structural Internal Loads" },
                { BuiltInCategory.OST_AreaLoads, "Area Loads" },
                { BuiltInCategory.OST_LineLoads, "Line Loads" },
                { BuiltInCategory.OST_PointLoads, "Point Loads" },
                { BuiltInCategory.OST_Loads, "Structural Loads" },
                { BuiltInCategory.OST_BeamSystemTags, "Structural Beam System Tags" },
                { BuiltInCategory.OST_FootingSpanDirectionSymbol, "Foundation Span Direction Symbol" },
                { BuiltInCategory.OST_SpanDirectionSymbol, "Span Direction Symbol" },
                { BuiltInCategory.OST_SpotElevSymbols, "Spot Elevation Symbols" },
                { BuiltInCategory.OST_TrussTags, "Structural Truss Tags" },
                { BuiltInCategory.OST_KeynoteTags, "Keynote Tags" },
                { BuiltInCategory.OST_DetailComponentTags, "Detail Item Tags" },
                { BuiltInCategory.OST_MaterialTags, "Material Tags" },
                { BuiltInCategory.OST_FloorTags, "Floor Tags" },
                { BuiltInCategory.OST_CurtaSystemTags, "Curtain System Tags" },
                { BuiltInCategory.OST_StairsTags, "Stair Tags" },
                { BuiltInCategory.OST_MultiCategoryTags, "Multi-Category Tags" },
                { BuiltInCategory.OST_PlantingTags, "Planting Tags" },
                { BuiltInCategory.OST_AreaTags, "Area Tags" },
                { BuiltInCategory.OST_StructuralFoundationTags, "Structural Foundation Tags" },
                { BuiltInCategory.OST_StructuralColumnTags, "Structural Column Tags" },
                { BuiltInCategory.OST_ParkingTags, "Parking Tags" },
                { BuiltInCategory.OST_SiteTags, "Site Tags" },
                { BuiltInCategory.OST_StructuralFramingTags, "Structural Framing Tags" },
                { BuiltInCategory.OST_SpecialityEquipmentTags, "Specialty Equipment Tags" },
                { BuiltInCategory.OST_GenericModelTags, "Generic Model Tags" },
                { BuiltInCategory.OST_CurtainWallPanelTags, "Curtain Panel Tags" },
                { BuiltInCategory.OST_WallTags, "Wall Tags" },
                { BuiltInCategory.OST_PlumbingFixtureTags, "Plumbing Fixture Tags" },
                { BuiltInCategory.OST_MechanicalEquipmentTags, "Mechanical Equipment Tags" },
                { BuiltInCategory.OST_LightingFixtureTags, "Lighting Fixture Tags" },
                { BuiltInCategory.OST_FurnitureSystemTags, "Furniture System Tags" },
                { BuiltInCategory.OST_FurnitureTags, "Furniture Tags" },
                { BuiltInCategory.OST_ElectricalFixtureTags, "Electrical Fixture Tags" },
                { BuiltInCategory.OST_ElectricalEquipmentTags, "Electrical Equipment Tags" },
                { BuiltInCategory.OST_CeilingTags, "Ceiling Tags" },
                { BuiltInCategory.OST_CaseworkTags, "Casework Tags" },
                { BuiltInCategory.OST_MEPSpaceColorFill, "Color Fill" },
                { BuiltInCategory.OST_MEPSpaceReferenceVisibility, "Reference" },
                { BuiltInCategory.OST_MEPSpaceInteriorFillVisibility, "Interior" },
                { BuiltInCategory.OST_MEPSpaces, "Spaces" },
                { BuiltInCategory.OST_MassShade, "Mass Shade" },
                { BuiltInCategory.OST_MassOpening, "Mass Opening" },
                { BuiltInCategory.OST_MassSkylights, "Mass Skylight" },
                { BuiltInCategory.OST_MassGlazing, "Mass Glazing" },
                { BuiltInCategory.OST_MassRoof, "Mass Roof" },
                { BuiltInCategory.OST_MassExteriorWall, "Mass Exterior Wall" },
                { BuiltInCategory.OST_MassInteriorWall, "Mass Interior Wall" },
                { BuiltInCategory.OST_MassZone, "Mass Zone" },
                { BuiltInCategory.OST_MassAreaFaceTags, "Mass Floor Tags" },
                { BuiltInCategory.OST_HostTemplate, "Host Template" }, // TODO check if this category is valid
                { BuiltInCategory.OST_MassFaceSplitter, "Mass Face Splitter" }, // TODO check if this category is valid
                { BuiltInCategory.OST_MassCutter, "Mass Cutter" }, // TODO check if this category is valid
                { BuiltInCategory.OST_ZoningEnvelope, "Zoning Envelope" }, // TODO check if this category is valid
                { BuiltInCategory.OST_MassTags, "Mass Tags" },
                { BuiltInCategory.OST_MassForm, "Form" },
                { BuiltInCategory.OST_MassFloor, "Mass Floor" },
                { BuiltInCategory.OST_Mass, "Mass" },
                { BuiltInCategory.OST_DividedSurface_PatternFill, "Pattern Fill" },
                { BuiltInCategory.OST_DividedSurface_PatternLines, "Pattern Lines" },
                { BuiltInCategory.OST_DividedSurface_Gridlines, "Gridlines" },
                { BuiltInCategory.OST_DividedSurface_Nodes, "Nodes" },
                { BuiltInCategory.OST_RampsDownArrow, "Down Arrow" },
                { BuiltInCategory.OST_RampsUpArrow, "Up Arrow" },
                { BuiltInCategory.OST_RampsDownText, "DOWN text" },
                { BuiltInCategory.OST_RampsUpText, "UP text" },
                { BuiltInCategory.OST_RampsStringerAboveCut, "Stringers Beyond Cut Line" },
                { BuiltInCategory.OST_RampsStringer, "Stringers" },
                { BuiltInCategory.OST_RampsAboveCut, "Ramps Beyond Cut Line" },
                { BuiltInCategory.OST_Areas, "Areas" },
                { BuiltInCategory.OST_ProjectInformation, "Project Information" },
                { BuiltInCategory.OST_Sheets, "Sheets" },
                { BuiltInCategory.OST_DetailComponents, "Detail Items" },
                { BuiltInCategory.OST_RoofSoffit, "Roof Soffits" },
                { BuiltInCategory.OST_EdgeSlab, "Slab Edges" },
                { BuiltInCategory.OST_Gutter, "Gutters" },
                { BuiltInCategory.OST_Fascia, "Fascias" },
                { BuiltInCategory.OST_Entourage, "Entourage" },
                { BuiltInCategory.OST_Planting, "Planting" },
                { BuiltInCategory.OST_StructuralStiffenerHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructuralColumnLocationLine, "Location Lines" },
                { BuiltInCategory.OST_StructuralFramingLocationLine, "Location Lines" },
                { BuiltInCategory.OST_StructuralStiffenerTags, "Structural Stiffener Tags" },
                { BuiltInCategory.OST_StructuralStiffener, "Structural Stiffeners" },
                { BuiltInCategory.OST_SpecialityEquipment, "Specialty Equipment" },
                { BuiltInCategory.OST_ColumnAnalyticalRigidLinks, "Rigid Links" },
                { BuiltInCategory.OST_SecondaryTopographyContours, "Secondary Contours" },
                { BuiltInCategory.OST_TopographyContours, "Primary Contours" },
                { BuiltInCategory.OST_TopographySurface, "Triangulation Edges" },
                { BuiltInCategory.OST_Topography, "Topography" },
                { BuiltInCategory.OST_StructuralTruss, "Structural Trusses" },
                { BuiltInCategory.OST_StructuralColumnStickSymbols, "Stick Symbols" },
                { BuiltInCategory.OST_HiddenStructuralColumnLines, "Hidden Lines" },
                { BuiltInCategory.OST_AnalyticalRigidLinks, "Rigid Links" },
                { BuiltInCategory.OST_StructuralColumns, "Structural Columns" },
                { BuiltInCategory.OST_HiddenStructuralFramingLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructuralFramingSystem, "Structural Beam Systems" },
                { BuiltInCategory.OST_StructuralFraming, "Structural Framing" },
                { BuiltInCategory.OST_HiddenStructuralFoundationLines, "Hidden Lines" },
                { BuiltInCategory.OST_StructuralFoundation, "Structural Foundations" },
                { BuiltInCategory.OST_SharedBasePoint, "Survey Point" },
                { BuiltInCategory.OST_ProjectBasePoint, "Project Base Point" },
                { BuiltInCategory.OST_SitePropertyLineSegmentTags, "Property Line Segment Tags" },
                { BuiltInCategory.OST_SitePropertyLineSegment, "Property Line Segments" },
                { BuiltInCategory.OST_SitePropertyTags, "Property Tags" },
                { BuiltInCategory.OST_SitePointBoundary, "Boundary Point" },
                { BuiltInCategory.OST_SiteProperty, "Property Lines" },
                { BuiltInCategory.OST_BuildingPad, "Pads" },
                { BuiltInCategory.OST_SitePoint, "Interior Point" },
                { BuiltInCategory.OST_Site, "Site" },
                { BuiltInCategory.OST_Roads, "Roads" },
                { BuiltInCategory.OST_Parking, "Parking" },
                { BuiltInCategory.OST_PlumbingFixtures, "Plumbing Fixtures" },
                { BuiltInCategory.OST_MechanicalEquipment, "Mechanical Equipment" },
                { BuiltInCategory.OST_LightingFixtureSource, "Light Source" },
                { BuiltInCategory.OST_LightingFixtures, "Lighting Fixtures" },
                { BuiltInCategory.OST_FurnitureSystems, "Furniture Systems" },
                { BuiltInCategory.OST_ElectricalFixtures, "Electrical Fixtures" },
                { BuiltInCategory.OST_ElectricalEquipment, "Electrical Equipment" },
                { BuiltInCategory.OST_Casework, "Casework" },
                { BuiltInCategory.OST_ShaftOpening, "Shaft Openings" },
                { BuiltInCategory.OST_FndSlabLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_FloorLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_WallLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_BraceLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_ColumnLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_BeamLocalCoordSys, "Local Coordinate System" },
                { BuiltInCategory.OST_MultiReferenceAnnotations, "Multi-Rebar Annotations" },
                { BuiltInCategory.OST_NodeAnalyticalTags, "Analytical Node Tags" },
                { BuiltInCategory.OST_LinkAnalyticalTags, "Analytical Link Tags" },
                { BuiltInCategory.OST_StairsSupports, "Supports" },
                { BuiltInCategory.OST_RailingHandRailAboveCut, "<Above> Handrails" },
                { BuiltInCategory.OST_RailingTopRailAboveCut, "<Above> Top Rails" },
                { BuiltInCategory.OST_RailingTermination, "Terminations" },
                { BuiltInCategory.OST_RailingSupport, "Supports" },
                { BuiltInCategory.OST_RailingHandRail, "Handrails" },
                { BuiltInCategory.OST_RailingTopRail, "Top Rails" },
                { BuiltInCategory.OST_StairsTriserNumbers, "Stair Tread/Riser Numbers" },
                { BuiltInCategory.OST_StairsSupportTags, "Stair Support Tags" },
                { BuiltInCategory.OST_StairsLandingTags, "Stair Landing Tags" },
                { BuiltInCategory.OST_StairsRunTags, "Stair Run Tags" },
                { BuiltInCategory.OST_StairsPathsAboveCut, "<Above> Up Arrows" },
                { BuiltInCategory.OST_StairsPaths, "Stair Paths" },
                { BuiltInCategory.OST_StairsRiserLinesAboveCut, "<Above> Riser Lines" },
                { BuiltInCategory.OST_StairsRiserLines, "Riser Lines" },
                { BuiltInCategory.OST_StairsOutlinesAboveCut, "<Above> Outlines" },
                { BuiltInCategory.OST_StairsOutlines, "Outlines" },
                { BuiltInCategory.OST_StairsNosingLinesAboveCut, "<Above> Nosing Lines" },
                { BuiltInCategory.OST_StairsNosingLines, "Nosing Lines" },
                { BuiltInCategory.OST_StairsCutMarksAboveCut, "<Above> Cut Marks" },
                { BuiltInCategory.OST_StairsCutMarks, "Cut Marks" },
                { BuiltInCategory.OST_StairsTrisers, "Treads/Risers" },
                { BuiltInCategory.OST_StairsLandings, "Landings" },
                { BuiltInCategory.OST_StairsRuns, "Runs" },
                { BuiltInCategory.OST_AdaptivePoints_Lines, "Lines" },
                { BuiltInCategory.OST_AdaptivePoints_Planes, "Planes" },
                { BuiltInCategory.OST_AdaptivePoints_Points, "Points" },
                { BuiltInCategory.OST_AdaptivePoints, "Adaptive Points" },
                { BuiltInCategory.OST_MEPSpaceSeparationLines, "<Space Separation>" },
                { BuiltInCategory.OST_InstanceDrivenLineStyle, "Instance Driven Line Style" }, // TODO check if this category is valid
                { BuiltInCategory.OST_ReferencePoints_Lines, "Lines" },
                { BuiltInCategory.OST_ReferencePoints_Planes, "Planes" },
                { BuiltInCategory.OST_ReferencePoints_Points, "Points" },
                { BuiltInCategory.OST_ReferencePoints, "Reference Points" },
                { BuiltInCategory.OST_Materials, "Materials" },
                { BuiltInCategory.OST_CeilingsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_CeilingsDefault, "Common Edges" },
                { BuiltInCategory.OST_CeilingsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_CeilingsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_CeilingsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_CeilingsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_CeilingsStructure, "Structure [1]" },
                { BuiltInCategory.OST_CeilingsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_FloorsInteriorEdges, "Interior Edges" },
                { BuiltInCategory.OST_FloorsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_HiddenFloorLines, "Hidden Lines" },
                { BuiltInCategory.OST_FloorsDefault, "Common Edges" },
                { BuiltInCategory.OST_FloorsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_FloorsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_FloorsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_FloorsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_FloorsStructure, "Structure [1]" },
                { BuiltInCategory.OST_FloorsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_RoofsInteriorEdges, "Interior Edges" },
                { BuiltInCategory.OST_RoofsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_RoofsDefault, "Common Edges" },
                { BuiltInCategory.OST_RoofsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_RoofsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_RoofsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_RoofsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_RoofsStructure, "Structure [1]" },
                { BuiltInCategory.OST_RoofsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_WallsCutPattern, "Cut Pattern" },
                { BuiltInCategory.OST_HiddenWallLines, "Hidden Lines" },
                { BuiltInCategory.OST_WallsDefault, "Common Edges" },
                { BuiltInCategory.OST_WallsFinish2, "Finish 2 [5]" },
                { BuiltInCategory.OST_WallsFinish1, "Finish 1 [4]" },
                { BuiltInCategory.OST_WallsSubstrate, "Substrate [2]" },
                { BuiltInCategory.OST_WallsInsulation, "Thermal/Air Layer [3]" },
                { BuiltInCategory.OST_WallsStructure, "Structure [1]" },
                { BuiltInCategory.OST_WallsMembrane, "Membrane Layer" },
                { BuiltInCategory.OST_ScheduleGraphics, "Schedule Graphics" },
                { BuiltInCategory.OST_RasterImages, "Raster Images" },
                { BuiltInCategory.OST_RoomColorFill, "Color Fill" },
                { BuiltInCategory.OST_ColorFillLegends, "Color Fill Legends" },
                { BuiltInCategory.OST_AnnotationCropSpecial, "Annotation Crop Boundary" },
                { BuiltInCategory.OST_CropBoundarySpecial, "Crop Boundaries" },
                { BuiltInCategory.OST_AnnotationCrop, "Annotation Crop Boundary" },
                { BuiltInCategory.OST_CalloutLeaderLine, "Callout Leader Line" },
                { BuiltInCategory.OST_CeilingsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_RoofsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_FloorsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_WallsSurfacePattern, "Surface Pattern" },
                { BuiltInCategory.OST_CalloutBoundary, "Callout Boundary" },
                { BuiltInCategory.OST_CalloutHeads, "Callout Heads" },
                { BuiltInCategory.OST_Callouts, "Callouts" },
                { BuiltInCategory.OST_CropBoundary, "Crop Boundaries" },
                { BuiltInCategory.OST_Elev, "Elevations" },
                { BuiltInCategory.OST_CLines, "Reference Planes" },
                { BuiltInCategory.OST_ViewportLabel, "View Titles" },
                { BuiltInCategory.OST_Viewports, "Viewports" },
                { BuiltInCategory.OST_Camera_Lines, "Cameras" },
                { BuiltInCategory.OST_MEPSpaceTags, "Space Tags" },
                { BuiltInCategory.OST_RoomTags, "Room Tags" },
                { BuiltInCategory.OST_DoorTags, "Door Tags" },
                { BuiltInCategory.OST_WindowTags, "Window Tags" },
                { BuiltInCategory.OST_SectionHeadWideLines, "Wide Lines" },
                { BuiltInCategory.OST_SectionHeadMediumLines, "Medium Lines" },
                { BuiltInCategory.OST_SectionHeadThinLines, "Thin Lines" },
                { BuiltInCategory.OST_SectionHeads, "Section Marks" },
                { BuiltInCategory.OST_ContourLabels, "Contour Labels" },
                { BuiltInCategory.OST_CurtaSystem, "Curtain Systems" },
                { BuiltInCategory.OST_CurtainGridsCurtaSystem, "Curtain System Grids" },
                { BuiltInCategory.OST_CurtainGridsSystem, "Curtain Grids System" }, // TODO check if this category is valid
                { BuiltInCategory.OST_CurtainGridsWall, "Curtain Wall Grids" },
                { BuiltInCategory.OST_CurtainGridsRoof, "Curtain Roof Grids" },
                { BuiltInCategory.OST_AnalysisDisplayStyle, "Analysis Display Style" },
                { BuiltInCategory.OST_AnalysisResults, "Analysis Results" },
                { BuiltInCategory.OST_RenderRegions, "Render Regions" },
                { BuiltInCategory.OST_SectionBox, "Section Boxes" },
                { BuiltInCategory.OST_TextNotes, "Text Notes" },
                { BuiltInCategory.OST_CenterLines, "<Centerline>" },
                { BuiltInCategory.OST_LinesBeyond, "<Beyond>" },
                { BuiltInCategory.OST_HiddenLines, "<Hidden>" },
                { BuiltInCategory.OST_DemolishedLines, "<Demolished>" },
                { BuiltInCategory.OST_OverheadLines, "<Overhead>" },
                { BuiltInCategory.OST_TitleBlockWideLines, "Wide Lines" },
                { BuiltInCategory.OST_TitleBlockMediumLines, "Medium Lines" },
                { BuiltInCategory.OST_TitleBlockThinLines, "Thin Lines" },
                { BuiltInCategory.OST_TitleBlocks, "Title Blocks" },
                { BuiltInCategory.OST_Views, "Views" },
                { BuiltInCategory.OST_PartHiddenLines, "Hidden Lines" },
                { BuiltInCategory.OST_PartTags, "Part Tags" },
                { BuiltInCategory.OST_Parts, "Parts" },
                { BuiltInCategory.OST_AssemblyTags, "Assembly Tags" },
                { BuiltInCategory.OST_Assemblies, "Assemblies" },
                { BuiltInCategory.OST_RoofTags, "Roof Tags" },
                { BuiltInCategory.OST_SpotSlopes, "Spot Slopes" },
                { BuiltInCategory.OST_SpotCoordinates, "Spot Coordinates" },
                { BuiltInCategory.OST_SpotElevations, "Spot Elevations" },
                { BuiltInCategory.OST_WeakDims, "Automatic Sketch Dimensions" },
                { BuiltInCategory.OST_Dimensions, "Dimensions" },
                { BuiltInCategory.OST_Levels, "Levels" },
                { BuiltInCategory.OST_DisplacementPath, "Displacement Path" },
                { BuiltInCategory.OST_GridChains, "Multi-segmented Grid" },
                { BuiltInCategory.OST_Grids, "Grids" },
                { BuiltInCategory.OST_BrokenSectionLine, "Broken Section Line" },
                { BuiltInCategory.OST_SectionLine, "Section Line" },
                { BuiltInCategory.OST_Sections, "Sections" },
                { BuiltInCategory.OST_ReferenceViewer, "View Reference" },
                { BuiltInCategory.OST_ReferenceViewerSymbol, "View Reference" },
                { BuiltInCategory.OST_ImportObjectStyles, "Imports in Families" },
                { BuiltInCategory.OST_MaskingRegion, "Masking Region" },
                { BuiltInCategory.OST_Matchline, "Matchline" },
                { BuiltInCategory.OST_PlanRegion, "Plan Region" },
                { BuiltInCategory.OST_FilledRegion, "Filled region" },
                { BuiltInCategory.OST_Cornices, "Wall Sweeps" },
                { BuiltInCategory.OST_Ramps, "Ramps" },
                { BuiltInCategory.OST_CurtainGrids, "Curtain Grids" },
                { BuiltInCategory.OST_CurtainWallMullions, "Curtain Wall Mullions" },
                { BuiltInCategory.OST_CurtainWallPanels, "Curtain Panels" },
                { BuiltInCategory.OST_AreaColorFill, "Color Fill" },
                { BuiltInCategory.OST_AreaReferenceVisibility, "Reference" },
                { BuiltInCategory.OST_AreaInteriorFillVisibility, "Interior Fill" },
                { BuiltInCategory.OST_RoomReferenceVisibility, "Reference" },
                { BuiltInCategory.OST_RoomInteriorFillVisibility, "Interior Fill" },
                { BuiltInCategory.OST_Rooms, "Rooms" },
                { BuiltInCategory.OST_GenericModel, "Generic Models" },
                { BuiltInCategory.OST_GenericAnnotation, "Generic Annotations" },
                { BuiltInCategory.OST_StairsRailingTags, "Railing Tags" },
                { BuiltInCategory.OST_StairsRailingAboveCut, "<Above> Railings Cut Line" },
                { BuiltInCategory.OST_StairsDownArrows, "Down Arrows" },
                { BuiltInCategory.OST_StairsUpArrows, "Up Arrows" },
                { BuiltInCategory.OST_StairsDownText, "DOWN Text" },
                { BuiltInCategory.OST_StairsRailingRail, "Rails" },
                { BuiltInCategory.OST_StairsRailingBaluster, "Balusters" },
                { BuiltInCategory.OST_StairsRailing, "Railings" },
                { BuiltInCategory.OST_StairsUpText, "UP Text" },
                { BuiltInCategory.OST_StairsSupportsAboveCut, "<Above> Supports" },
                { BuiltInCategory.OST_StairsStringerCarriage, "Supports" },
                { BuiltInCategory.OST_Stairs, "Stairs" },
                { BuiltInCategory.OST_GuideGrid, "Guide Grid" },
                { BuiltInCategory.OST_Columns, "Columns" },
                { BuiltInCategory.OST_ReferenceLines, "Reference Lines" },
                { BuiltInCategory.OST_IOSNotSilhouette, "IOS Not Silhouette" }, // TODO check if this category is valid
                { BuiltInCategory.OST_Furniture, "Furniture" },
                { BuiltInCategory.OST_AreaSchemeLines, "<Area Boundary>" },
                { BuiltInCategory.OST_GenericLines, "Lines" },
                { BuiltInCategory.OST_InsulationLines, "Insulation Batting Lines" },
                { BuiltInCategory.OST_RoomSeparationLines, "<Room Separation>" },
                { BuiltInCategory.OST_AxisOfRotation, "Axis of Rotation" },
                { BuiltInCategory.OST_InvisibleLines, "Invisible Lines" }, // TODO check if this category is valid
                { BuiltInCategory.OST_Lines, "Lines" },
                { BuiltInCategory.OST_SketchLines, "<Sketch>" },
                { BuiltInCategory.OST_CurvesWideLines, "Wide Lines" },
                { BuiltInCategory.OST_CurvesMediumLines, "Medium Lines" },
                { BuiltInCategory.OST_CurvesThinLines, "Thin Lines" },
                { BuiltInCategory.OST_Ceilings, "Ceilings" },
                { BuiltInCategory.OST_Roofs, "Roofs" },
                { BuiltInCategory.OST_Floors, "Floors" },
                { BuiltInCategory.OST_DoorsGlassProjection, "Glass" },
                { BuiltInCategory.OST_DoorsFrameMullionProjection, "Frame/Mullion" },
                { BuiltInCategory.OST_DoorsOpeningProjection, "Opening" },
                { BuiltInCategory.OST_DoorsPanelProjection, "Panel" },
                { BuiltInCategory.OST_Doors, "Doors" },
                { BuiltInCategory.OST_WindowsOpeningProjection, "Opening" },
                { BuiltInCategory.OST_WindowsSillHeadProjection, "Sill/Head" },
                { BuiltInCategory.OST_WindowsFrameMullionProjection, "Frame/Mullion" },
                { BuiltInCategory.OST_WindowsGlassProjection, "Glass" },
                { BuiltInCategory.OST_Windows, "Windows" },
                { BuiltInCategory.OST_Walls, "Walls" },
            };
        }

        /// <summary>
        /// Tries to get the name of a built-in category.
        /// </summary>
        /// <param name="category">The category.</param>
        /// <param name="categoryName">Name of the category.</param>
        /// <returns></returns>
        public static bool TryGetCategoryName(this BuiltInCategory category, out string categoryName)
        {
            return _knownCategories.TryGetValue(category, out categoryName);
        }
    }
}