// Decompiled with JetBrains decompiler
// Type: Autodesk.Revit.DB.UnitType
// Assembly: RevitAPI, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null
// ReSharper disable InconsistentNaming

namespace CodeCave.Revit.Toolkit
{
    /// <summary>The type of physical quantity to be measured, for example length or force.</summary>
    /// <remarks>
    ///      <para>Some unit types represent fundamental physical quantities to
    /// be measured, for example UT_Length, UT_Area, UT_Mass, or
    /// UT_Force.</para>
    ///      <para>Other unit types exist to provide an alternate set of unit
    /// settings for a physical quantity.  For example, UT_HVAC_DuctSize is
    /// used for measuring sizes of ducts, UT_PipeSize is used for
    /// measuring sizes of pipes, and UT_SheetLength is used for measuring
    /// distances on a piece of paper.  All of those are lengths and could
    /// use UT_Length, but they are typically measured using different
    /// units or to a different degree of accuracy compared with typical
    /// lengths in a building.  By using different unit types, the Units
    /// class can have different default settings for measuring values of
    /// the same physical quantity.</para>
    ///    </remarks>
    public enum UnitType
    {
        UT_Undefined = -2,
        UT_Custom = -1,
        UT_Length = 0,
        UT_Area = 1,
        UT_Volume = 2,
        UT_Angle = 3,
        UT_Number = 4,
        UT_SheetLength = 5,
        UT_SiteAngle = 6,
        UT_HVAC_Density = 7,
        UT_HVAC_Energy = 8,
        UT_HVAC_Friction = 9,
        UT_HVAC_Power = 10,
        UT_HVAC_Power_Density = 11,
        UT_HVAC_Pressure = 12,
        UT_HVAC_Temperature = 13,
        UT_HVAC_Velocity = 14,
        UT_HVAC_Airflow = 15,
        UT_HVAC_DuctSize = 16,
        UT_HVAC_CrossSection = 17,
        UT_HVAC_HeatGain = 18,
        UT_Electrical_Current = 19,
        UT_Electrical_Potential = 20,
        UT_Electrical_Frequency = 21,
        UT_Electrical_Illuminance = 22,
        UT_Electrical_Luminous_Flux = 23,
        UT_Electrical_Power = 24,
        UT_HVAC_Roughness = 25,
        UT_Force = 26,
        UT_LinearForce = 27,
        UT_AreaForce = 28,
        UT_Moment = 29,
        UT_ForceScale = 30,
        UT_LinearForceScale = 31,
        UT_AreaForceScale = 32,
        UT_MomentScale = 33,
        UT_Electrical_Apparent_Power = 34,
        UT_Electrical_Power_Density = 35,
        UT_Piping_Density = 36,
        UT_Piping_Flow = 37,
        UT_Piping_Friction = 38,
        UT_Piping_Pressure = 39,
        UT_Piping_Temperature = 40,
        UT_Piping_Velocity = 41,
        UT_Piping_Viscosity = 42,
        UT_PipeSize = 43,
        UT_Piping_Roughness = 44,
        UT_Stress = 45,
        UT_UnitWeight = 46,
        UT_ThermalExpansion = 47,
        UT_LinearMoment = 48,
        UT_LinearMomentScale = 49,
        UT_ForcePerLength = 50,
        UT_ForceLengthPerAngle = 51,
        UT_LinearForcePerLength = 52,
        UT_LinearForceLengthPerAngle = 53,
        UT_AreaForcePerLength = 54,
        UT_Piping_Volume = 55,
        UT_HVAC_Viscosity = 56,
        UT_HVAC_CoefficientOfHeatTransfer = 57,
        UT_HVAC_Airflow_Density = 58,
        UT_Slope = 59,
        UT_HVAC_Cooling_Load = 60,
        UT_HVAC_Cooling_Load_Divided_By_Area = 61,
        UT_HVAC_Cooling_Load_Divided_By_Volume = 62,
        UT_HVAC_Heating_Load = 63,
        UT_HVAC_Heating_Load_Divided_By_Area = 64,
        UT_HVAC_Heating_Load_Divided_By_Volume = 65,
        UT_HVAC_Airflow_Divided_By_Volume = 66,
        UT_HVAC_Airflow_Divided_By_Cooling_Load = 67,
        UT_HVAC_Area_Divided_By_Cooling_Load = 68,
        UT_WireSize = 69,
        UT_HVAC_Slope = 70,
        UT_Piping_Slope = 71,
        UT_Currency = 72,
        UT_Electrical_Efficacy = 73,
        UT_Electrical_Wattage = 74,
        UT_Color_Temperature = 75,
        UT_DecSheetLength = 76,
        UT_Electrical_Luminous_Intensity = 77,
        UT_Electrical_Luminance = 78,
        UT_HVAC_Area_Divided_By_Heating_Load = 79,
        UT_HVAC_Factor = 80,
        UT_Electrical_Temperature = 81,
        UT_Electrical_CableTraySize = 82,
        UT_Electrical_ConduitSize = 83,
        UT_Reinforcement_Volume = 84,
        UT_Reinforcement_Length = 85,
        UT_Electrical_Demand_Factor = 86,
        UT_HVAC_DuctInsulationThickness = 87,
        UT_HVAC_DuctLiningThickness = 88,
        UT_PipeInsulationThickness = 89,
        UT_HVAC_ThermalResistance = 90,
        UT_HVAC_ThermalMass = 91,
        UT_Acceleration = 92,
        UT_Bar_Diameter = 93,
        UT_Crack_Width = 94,
        UT_Displacement_Deflection = 95,
        UT_Energy = 96,
        UT_Structural_Frequency = 97,
        UT_Mass = 98,
        UT_Mass_per_Unit_Length = 99,
        UT_Moment_of_Inertia = 100,
        UT_Surface_Area = 101,
        UT_Period = 102,
        UT_Pulsation = 103,
        UT_Reinforcement_Area = 104,
        UT_Reinforcement_Area_per_Unit_Length = 105,
        UT_Reinforcement_Cover = 106,
        UT_Reinforcement_Spacing = 107,
        UT_Rotation = 108,
        UT_Section_Area = 109,
        UT_Section_Dimension = 110,
        UT_Section_Modulus = 111,
        UT_Section_Property = 112,
        UT_Structural_Velocity = 113,
        UT_Warping_Constant = 114,
        UT_Weight = 115,
        UT_Weight_per_Unit_Length = 116,
        UT_HVAC_ThermalConductivity = 117,
        UT_HVAC_SpecificHeat = 118,
        UT_HVAC_SpecificHeatOfVaporization = 119,
        UT_HVAC_Permeability = 120,
        UT_Electrical_Resistivity = 121,
        UT_MassDensity = 122,
        UT_MassPerUnitArea = 123,
        UT_Pipe_Dimension = 124,
        UT_PipeMass = 125,
        UT_PipeMassPerUnitLength = 126,
        UT_HVAC_TemperatureDifference = 127,
        UT_Piping_TemperatureDifference = 128,
        UT_Electrical_TemperatureDifference = 129,
    }
}
