// Decompiled with JetBrains decompiler
// Type: Autodesk.Revit.DB.UnitType
// Assembly: RevitAPI, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null
// ReSharper disable InconsistentNaming

using System.Collections.Generic;
using System.Linq;

namespace CodeCave.Revit.Toolkit
{
    /// <summary>The type of physical quantity to be measured, for example length or force.</summary>
    /// <remarks>
    ///      <para>Some unit types represent fundamental physical quantities to
    /// be measured, for example UT_Length, UT_Area, UT_Mass, or
    /// UT_Force.</para>
    ///      <para>Other unit types exist to provide an alternate set of unit
    /// settings for a physical quantity.  For example, UT_HVAC_DuctSize is
    /// used for measuring sizes of ducts, UT_PipeSize is used for
    /// measuring sizes of pipes, and UT_SheetLength is used for measuring
    /// distances on a piece of paper.  All of those are lengths and could
    /// use UT_Length, but they are typically measured using different
    /// units or to a different degree of accuracy compared with typical
    /// lengths in a building.  By using different unit types, the Units
    /// class can have different default settings for measuring values of
    /// the same physical quantity.</para>
    ///    </remarks>
    public enum UnitType
    {
        UT_Undefined = -2,
        UT_Custom = -1,
        UT_Length = 0,
        UT_Area = 1,
        UT_Volume = 2,
        UT_Angle = 3,
        UT_Number = 4,
        UT_SheetLength = 5,
        UT_SiteAngle = 6,
        UT_HVAC_Density = 7,
        UT_HVAC_Energy = 8,
        UT_HVAC_Friction = 9,
        UT_HVAC_Power = 10,
        UT_HVAC_Power_Density = 11,
        UT_HVAC_Pressure = 12,
        UT_HVAC_Temperature = 13,
        UT_HVAC_Velocity = 14,
        UT_HVAC_Airflow = 15,
        UT_HVAC_DuctSize = 16,
        UT_HVAC_CrossSection = 17,
        UT_HVAC_HeatGain = 18,
        UT_Electrical_Current = 19,
        UT_Electrical_Potential = 20,
        UT_Electrical_Frequency = 21,
        UT_Electrical_Illuminance = 22,
        UT_Electrical_Luminous_Flux = 23,
        UT_Electrical_Power = 24,
        UT_HVAC_Roughness = 25,
        UT_Force = 26,
        UT_LinearForce = 27,
        UT_AreaForce = 28,
        UT_Moment = 29,
        UT_ForceScale = 30,
        UT_LinearForceScale = 31,
        UT_AreaForceScale = 32,
        UT_MomentScale = 33,
        UT_Electrical_Apparent_Power = 34,
        UT_Electrical_Power_Density = 35,
        UT_Piping_Density = 36,
        UT_Piping_Flow = 37,
        UT_Piping_Friction = 38,
        UT_Piping_Pressure = 39,
        UT_Piping_Temperature = 40,
        UT_Piping_Velocity = 41,
        UT_Piping_Viscosity = 42,
        UT_PipeSize = 43,
        UT_Piping_Roughness = 44,
        UT_Stress = 45,
        UT_UnitWeight = 46,
        UT_ThermalExpansion = 47,
        UT_LinearMoment = 48,
        UT_LinearMomentScale = 49,
        UT_ForcePerLength = 50,
        UT_ForceLengthPerAngle = 51,
        UT_LinearForcePerLength = 52,
        UT_LinearForceLengthPerAngle = 53,
        UT_AreaForcePerLength = 54,
        UT_Piping_Volume = 55,
        UT_HVAC_Viscosity = 56,
        UT_HVAC_CoefficientOfHeatTransfer = 57,
        UT_HVAC_Airflow_Density = 58,
        UT_Slope = 59,
        UT_HVAC_Cooling_Load = 60,
        UT_HVAC_Cooling_Load_Divided_By_Area = 61,
        UT_HVAC_Cooling_Load_Divided_By_Volume = 62,
        UT_HVAC_Heating_Load = 63,
        UT_HVAC_Heating_Load_Divided_By_Area = 64,
        UT_HVAC_Heating_Load_Divided_By_Volume = 65,
        UT_HVAC_Airflow_Divided_By_Volume = 66,
        UT_HVAC_Airflow_Divided_By_Cooling_Load = 67,
        UT_HVAC_Area_Divided_By_Cooling_Load = 68,
        UT_WireSize = 69,
        UT_HVAC_Slope = 70,
        UT_Piping_Slope = 71,
        UT_Currency = 72,
        UT_Electrical_Efficacy = 73,
        UT_Electrical_Wattage = 74,
        UT_Color_Temperature = 75,
        UT_DecSheetLength = 76,
        UT_Electrical_Luminous_Intensity = 77,
        UT_Electrical_Luminance = 78,
        UT_HVAC_Area_Divided_By_Heating_Load = 79,
        UT_HVAC_Factor = 80,
        UT_Electrical_Temperature = 81,
        UT_Electrical_CableTraySize = 82,
        UT_Electrical_ConduitSize = 83,
        UT_Reinforcement_Volume = 84,
        UT_Reinforcement_Length = 85,
        UT_Electrical_Demand_Factor = 86,
        UT_HVAC_DuctInsulationThickness = 87,
        UT_HVAC_DuctLiningThickness = 88,
        UT_PipeInsulationThickness = 89,
        UT_HVAC_ThermalResistance = 90,
        UT_HVAC_ThermalMass = 91,
        UT_Acceleration = 92,
        UT_Bar_Diameter = 93,
        UT_Crack_Width = 94,
        UT_Displacement_Deflection = 95,
        UT_Energy = 96,
        UT_Structural_Frequency = 97,
        UT_Mass = 98,
        UT_Mass_per_Unit_Length = 99,
        UT_Moment_of_Inertia = 100,
        UT_Surface_Area = 101,
        UT_Period = 102,
        UT_Pulsation = 103,
        UT_Reinforcement_Area = 104,
        UT_Reinforcement_Area_per_Unit_Length = 105,
        UT_Reinforcement_Cover = 106,
        UT_Reinforcement_Spacing = 107,
        UT_Rotation = 108,
        UT_Section_Area = 109,
        UT_Section_Dimension = 110,
        UT_Section_Modulus = 111,
        UT_Section_Property = 112,
        UT_Structural_Velocity = 113,
        UT_Warping_Constant = 114,
        UT_Weight = 115,
        UT_Weight_per_Unit_Length = 116,
        UT_HVAC_ThermalConductivity = 117,
        UT_HVAC_SpecificHeat = 118,
        UT_HVAC_SpecificHeatOfVaporization = 119,
        UT_HVAC_Permeability = 120,
        UT_Electrical_Resistivity = 121,
        UT_MassDensity = 122,
        UT_MassPerUnitArea = 123,
        UT_Pipe_Dimension = 124,
        UT_PipeMass = 125,
        UT_PipeMassPerUnitLength = 126,
        UT_HVAC_TemperatureDifference = 127,
        UT_Piping_TemperatureDifference = 128,
        UT_Electrical_TemperatureDifference = 129,
    }

    public static class UnitTypeExtensions
    {
        private static readonly Dictionary<UnitType, string> _utToCatalog;
        private static readonly Dictionary<UnitType, UnitGroup> _utGroups;

        /// <summary>
        /// Initializes the <see cref="UnitTypeExtensions"/> class.
        /// </summary>
        static UnitTypeExtensions()
        {
            _utToCatalog = new Dictionary<UnitType, string>
            {
                { UnitType.UT_Length, "LENGTH" },
                { UnitType.UT_Area, "AREA" },
                { UnitType.UT_Volume, "VOLUME" },
                { UnitType.UT_Angle, "ANGLE" },
                { UnitType.UT_Number, "NUMBER" },
                { UnitType.UT_SheetLength, "" },
                { UnitType.UT_SiteAngle, "" },
                { UnitType.UT_HVAC_Density, "HVAC_DENSITY" },
                { UnitType.UT_HVAC_Energy, "HVAC_ENERGY" },
                { UnitType.UT_HVAC_Friction, "HVAC_FRICTION" },
                { UnitType.UT_HVAC_Power, "HVAC_POWER" },
                { UnitType.UT_HVAC_Power_Density, "HVAC_POWER_DENSITY" },
                { UnitType.UT_HVAC_Pressure, "HVAC_PRESSURE" },
                { UnitType.UT_HVAC_Temperature, "HVAC_TEMPERATURE" },
                { UnitType.UT_HVAC_Velocity, "HVAC_VELOCITY" },
                { UnitType.UT_HVAC_Airflow, "HVAC_AIR_FLOW" },
                { UnitType.UT_HVAC_DuctSize, "HVAC_DUCT_SIZE" },
                { UnitType.UT_HVAC_CrossSection, "HVAC_CROSS_SECTION" },
                { UnitType.UT_HVAC_HeatGain, "HVAC_HEAT_GAIN" },
                { UnitType.UT_Electrical_Current, "ELECTRICAL_CURRENT" },
                { UnitType.UT_Electrical_Potential, "ELECTRICAL_POTENTIAL" },
                { UnitType.UT_Electrical_Frequency, "ELECTRICAL_FREQUENCY" },
                { UnitType.UT_Electrical_Illuminance, "ELECTRICAL_ILLUMINANCE" },
                { UnitType.UT_Electrical_Luminous_Flux, "ELECTRICAL_LUMINOUS_FLUX" },
                { UnitType.UT_Electrical_Power, "ELECTRICAL_POWER" },
                { UnitType.UT_HVAC_Roughness, "HVAC_ROUGHNESS" },
                { UnitType.UT_Force, "FORCE" },
                { UnitType.UT_LinearForce, "LINEAR_FORCE" },
                { UnitType.UT_AreaForce, "AREA_FORCE" },
                { UnitType.UT_Moment, "MOMENT" },
                { UnitType.UT_ForceScale, "" },
                { UnitType.UT_LinearForceScale, "" },
                { UnitType.UT_AreaForceScale, "" },
                { UnitType.UT_MomentScale, "" },
                { UnitType.UT_Electrical_Apparent_Power, "ELECTRICAL_APPARENT_POWER" },
                { UnitType.UT_Electrical_Power_Density, "ELECTRICAL_POWER_DENSITY" },
                { UnitType.UT_Piping_Density, "PIPING_DENSITY" },
                { UnitType.UT_Piping_Flow, "PIPING_FLOW" },
                { UnitType.UT_Piping_Friction, "PIPING_FRICTION" },
                { UnitType.UT_Piping_Pressure, "PIPING_PRESSURE" },
                { UnitType.UT_Piping_Temperature, "PIPING_TEMPERATURE" },
                { UnitType.UT_Piping_Velocity, "PIPING_VELOCITY" },
                { UnitType.UT_Piping_Viscosity, "PIPING_VISCOSITY" },
                { UnitType.UT_PipeSize, "PIPE_SIZE" },
                { UnitType.UT_Piping_Roughness, "PIPING_ROUGHNESS" },
                { UnitType.UT_Stress, "STRESS" },
                { UnitType.UT_UnitWeight, "UNIT_WEIGHT" },
                { UnitType.UT_ThermalExpansion, "THERMAL_EXPANSION_COEFFICIENT" },
                { UnitType.UT_LinearMoment, "LINEAR_MOMENT" },
                { UnitType.UT_LinearMomentScale, "" },
                { UnitType.UT_ForcePerLength, "POINT_SPRING_COEFFICIENT" },
                { UnitType.UT_ForceLengthPerAngle, "ROTATIONAL_POINT_SPRING_COEFFICIENT" },
                { UnitType.UT_LinearForcePerLength, "LINEAR_SPRING_COEFFICIENT" },
                { UnitType.UT_LinearForceLengthPerAngle, "ROTATIONAL_LINEAR_SPRING_COEFFICIENT" },
                { UnitType.UT_AreaForcePerLength, "AREA_SPRING_COEFFICIENT" },
                { UnitType.UT_Piping_Volume, "PIPING_VOLUME" },
                { UnitType.UT_HVAC_Viscosity, "HVAC_VISCOSITY" },
                { UnitType.UT_HVAC_CoefficientOfHeatTransfer, "HVAC_COEFFICIENT_OF_HEAT_TRANSFER" },
                { UnitType.UT_HVAC_Airflow_Density, "HVAC_AIRFLOW_DENSITY" },
                { UnitType.UT_Slope, "SLOPE" },
                { UnitType.UT_HVAC_Cooling_Load, "HVAC_COOLING_LOAD" },
                { UnitType.UT_HVAC_Cooling_Load_Divided_By_Area, "HVAC_COOLING_LOAD_DIVIDED_BY_AREA" },
                { UnitType.UT_HVAC_Cooling_Load_Divided_By_Volume, "HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME" },
                { UnitType.UT_HVAC_Heating_Load, "HVAC_HEATING_LOAD" },
                { UnitType.UT_HVAC_Heating_Load_Divided_By_Area, "HVAC_HEATING_LOAD_DIVIDED_BY_AREA" },
                { UnitType.UT_HVAC_Heating_Load_Divided_By_Volume, "HVAC_HEATING_LOAD_DIVIDED_BY_VOLUME" },
                { UnitType.UT_HVAC_Airflow_Divided_By_Volume, "HVAC_AIRFLOW_DIVIDED_BY_VOLUME" },
                { UnitType.UT_HVAC_Airflow_Divided_By_Cooling_Load, "HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD" },
                { UnitType.UT_HVAC_Area_Divided_By_Cooling_Load, "HVAC_AREA_DIVIDED_BY_COOLING_LOAD" },
                { UnitType.UT_WireSize, "WIRE_SIZE" },
                { UnitType.UT_HVAC_Slope, "HVAC_SLOPE" },
                { UnitType.UT_Piping_Slope, "PIPING_SLOPE" },
                { UnitType.UT_Currency, "CURRENCY" },
                { UnitType.UT_Electrical_Efficacy, "ELECTRICAL_EFFICACY" },
                { UnitType.UT_Electrical_Wattage, "ELECTRICAL_WATTAGE" },
                { UnitType.UT_Color_Temperature, "COLOR_TEMPERATURE" },
                { UnitType.UT_DecSheetLength, "" },
                { UnitType.UT_Electrical_Luminous_Intensity, "ELECTRICAL_LUMINOUS_INTENSITY" },
                { UnitType.UT_Electrical_Luminance, "ELECTRICAL_LUMINANCE" },
                { UnitType.UT_HVAC_Area_Divided_By_Heating_Load, "HVAC_AREA_DIVIDED_BY_HEATING_LOAD" },
                { UnitType.UT_HVAC_Factor, "HVAC_FACTOR" },
                { UnitType.UT_Electrical_Temperature, "ELECTRICAL_TEMPERATURE" },
                { UnitType.UT_Electrical_CableTraySize, "CABLETRAY_SIZE" },
                { UnitType.UT_Electrical_ConduitSize, "CONDUIT_SIZE" },
                { UnitType.UT_Reinforcement_Volume, "REINFORCEMENT_VOLUME" },
                { UnitType.UT_Reinforcement_Length, "REINFORCEMENT_LENGTH" },
                { UnitType.UT_Electrical_Demand_Factor, "ELECTRICAL_DEMAND_FACTOR" },
                { UnitType.UT_HVAC_DuctInsulationThickness, "HVAC_DUCT_INSULATION_THICKNESS" },
                { UnitType.UT_HVAC_DuctLiningThickness, "HVAC_DUCT_LINING_THICKNESS" },
                { UnitType.UT_PipeInsulationThickness, "PIPE_INSUlATION_THICKNESS" },
                { UnitType.UT_HVAC_ThermalResistance, "HVAC_THERMAL_RESISTANCE" },
                { UnitType.UT_HVAC_ThermalMass, "HVAC_THERMAL_MASS" },
                { UnitType.UT_Acceleration, "ACCELERATION" },
                { UnitType.UT_Bar_Diameter, "BAR_DIAMETER" },
                { UnitType.UT_Crack_Width, "CRACK_WIDTH" },
                { UnitType.UT_Displacement_Deflection, "DISPLACEMENT/DEFLECTION" },
                { UnitType.UT_Energy, "ENERGY" },
                { UnitType.UT_Structural_Frequency, "STRUCTURAL_FREQUENCY" },
                { UnitType.UT_Mass, "MASS" },
                { UnitType.UT_Mass_per_Unit_Length, "MASS_PER_UNIT_LENGTH" },
                { UnitType.UT_Moment_of_Inertia, "MOMENT_OF_INERTIA" },
                { UnitType.UT_Surface_Area, "SURFACE_AREA" },
                { UnitType.UT_Period, "PERIOD" },
                { UnitType.UT_Pulsation, "PULSATION" },
                { UnitType.UT_Reinforcement_Area, "REINFORCEMENT_AREA" },
                { UnitType.UT_Reinforcement_Area_per_Unit_Length, "REINFORCEMENT_AREA_PER_UNIT_LENGTH" },
                { UnitType.UT_Reinforcement_Cover, "REINFORCEMENT_COVER" },
                { UnitType.UT_Reinforcement_Spacing, "REINFORCEMENT_SPACING" },
                { UnitType.UT_Rotation, "ROTATION" },
                { UnitType.UT_Section_Area, "SECTION_AREA" },
                { UnitType.UT_Section_Dimension, "SECTION_DIMENSION" },
                { UnitType.UT_Section_Modulus, "SECTION_MODULUS" },
                { UnitType.UT_Section_Property, "SECTION_PROPERTY" },
                { UnitType.UT_Structural_Velocity, "VELOCITY" },
                { UnitType.UT_Warping_Constant, "WARPING_CONSTANT" },
                { UnitType.UT_Weight, "WEIGHT" },
                { UnitType.UT_Weight_per_Unit_Length, "WEIGHT_PER_UNIT_LENGTH" },
                { UnitType.UT_HVAC_ThermalConductivity, "HVAC_THERMAL_CONDUCTIVITY" },
                { UnitType.UT_HVAC_SpecificHeat, "HVAC_SPECIFIC_HEAT" },
                { UnitType.UT_HVAC_SpecificHeatOfVaporization, "HVAC_SPECIFIC_HEAT_OF_VAPORIZATION" },
                { UnitType.UT_HVAC_Permeability, "HVAC_PERMEABILITY" },
                { UnitType.UT_Electrical_Resistivity, "ELECTRICAL_RESISTIVITY" },
                { UnitType.UT_MassDensity, "MASS_DENSITY" },
                { UnitType.UT_MassPerUnitArea, "MASS_PER_UNIT_AREA" },
                { UnitType.UT_Pipe_Dimension, "PIPE_DIMENSION" },
                { UnitType.UT_PipeMass, "PIPE_MASS" },
                { UnitType.UT_PipeMassPerUnitLength, "PIPE_MASS_PER_UNIT_LENGTH" },
                { UnitType.UT_HVAC_TemperatureDifference, "HVAC_TEMPERATURE_DIFFERENCE" },
                { UnitType.UT_Piping_TemperatureDifference, "PIPING_TEMPERATURE_DIFFERENCE" },
                { UnitType.UT_Electrical_TemperatureDifference, "ELECTRICAL_TEMPERATURE_DIFFERENCE" },

            };

            _utGroups = new Dictionary<UnitType, UnitGroup>
            {
                { UnitType.UT_Length, UnitGroup.Common },
                { UnitType.UT_Area, UnitGroup.Common },
                { UnitType.UT_Volume, UnitGroup.Common },
                { UnitType.UT_Angle, UnitGroup.Common },
                { UnitType.UT_Number, UnitGroup.Common },
                { UnitType.UT_SheetLength, UnitGroup.Common },
                { UnitType.UT_SiteAngle, UnitGroup.Common },
                { UnitType.UT_HVAC_Density, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Energy, UnitGroup.Energy },
                { UnitType.UT_HVAC_Friction, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Power, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Power_Density, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Pressure, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Temperature, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Velocity, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Airflow, UnitGroup.HVAC },
                { UnitType.UT_HVAC_DuctSize, UnitGroup.HVAC },
                { UnitType.UT_HVAC_CrossSection, UnitGroup.HVAC },
                { UnitType.UT_HVAC_HeatGain, UnitGroup.HVAC },
                { UnitType.UT_Electrical_Current, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Potential, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Frequency, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Illuminance, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Luminous_Flux, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Power, UnitGroup.Electrical },
                { UnitType.UT_HVAC_Roughness, UnitGroup.HVAC },
                { UnitType.UT_Force, UnitGroup.Structural },
                { UnitType.UT_LinearForce, UnitGroup.Structural },
                { UnitType.UT_AreaForce, UnitGroup.Structural },
                { UnitType.UT_Moment, UnitGroup.Structural },
                { UnitType.UT_ForceScale, UnitGroup.Structural },
                { UnitType.UT_LinearForceScale, UnitGroup.Structural },
                { UnitType.UT_AreaForceScale, UnitGroup.Structural },
                { UnitType.UT_MomentScale, UnitGroup.Structural },
                { UnitType.UT_Electrical_Apparent_Power, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Power_Density, UnitGroup.Electrical },
                { UnitType.UT_Piping_Density, UnitGroup.Piping },
                { UnitType.UT_Piping_Flow, UnitGroup.Piping },
                { UnitType.UT_Piping_Friction, UnitGroup.Piping },
                { UnitType.UT_Piping_Pressure, UnitGroup.Piping },
                { UnitType.UT_Piping_Temperature, UnitGroup.Piping },
                { UnitType.UT_Piping_Velocity, UnitGroup.Piping },
                { UnitType.UT_Piping_Viscosity, UnitGroup.Piping },
                { UnitType.UT_PipeSize, UnitGroup.Piping },
                { UnitType.UT_Piping_Roughness, UnitGroup.Piping },
                { UnitType.UT_Stress, UnitGroup.Structural },
                { UnitType.UT_UnitWeight, UnitGroup.Structural },
                { UnitType.UT_ThermalExpansion, UnitGroup.Structural },
                { UnitType.UT_LinearMoment, UnitGroup.Structural },
                { UnitType.UT_LinearMomentScale, UnitGroup.Structural },
                { UnitType.UT_ForcePerLength, UnitGroup.Structural },
                { UnitType.UT_ForceLengthPerAngle, UnitGroup.Structural },
                { UnitType.UT_LinearForcePerLength, UnitGroup.Structural },
                { UnitType.UT_LinearForceLengthPerAngle, UnitGroup.Structural },
                { UnitType.UT_AreaForcePerLength, UnitGroup.Structural },
                { UnitType.UT_Piping_Volume, UnitGroup.Piping },
                { UnitType.UT_HVAC_Viscosity, UnitGroup.HVAC },
                { UnitType.UT_HVAC_CoefficientOfHeatTransfer, UnitGroup.Energy },
                { UnitType.UT_HVAC_Airflow_Density, UnitGroup.HVAC },
                { UnitType.UT_Slope, UnitGroup.Common },
                { UnitType.UT_HVAC_Cooling_Load, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Cooling_Load_Divided_By_Area, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Cooling_Load_Divided_By_Volume, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Heating_Load, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Heating_Load_Divided_By_Area, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Heating_Load_Divided_By_Volume, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Airflow_Divided_By_Volume, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Airflow_Divided_By_Cooling_Load, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Area_Divided_By_Cooling_Load, UnitGroup.HVAC },
                { UnitType.UT_WireSize, UnitGroup.Electrical },
                { UnitType.UT_HVAC_Slope, UnitGroup.HVAC },
                { UnitType.UT_Piping_Slope, UnitGroup.Piping },
                { UnitType.UT_Currency, UnitGroup.Common },
                { UnitType.UT_Electrical_Efficacy, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Wattage, UnitGroup.Electrical },
                { UnitType.UT_Color_Temperature, UnitGroup.Electrical },
                { UnitType.UT_DecSheetLength, UnitGroup.Common },
                { UnitType.UT_Electrical_Luminous_Intensity, UnitGroup.Electrical },
                { UnitType.UT_Electrical_Luminance, UnitGroup.Electrical },
                { UnitType.UT_HVAC_Area_Divided_By_Heating_Load, UnitGroup.HVAC },
                { UnitType.UT_HVAC_Factor, UnitGroup.HVAC },
                { UnitType.UT_Electrical_Temperature, UnitGroup.Electrical },
                { UnitType.UT_Electrical_CableTraySize, UnitGroup.Electrical },
                { UnitType.UT_Electrical_ConduitSize, UnitGroup.Electrical },
                { UnitType.UT_Reinforcement_Volume, UnitGroup.Structural },
                { UnitType.UT_Reinforcement_Length, UnitGroup.Structural },
                { UnitType.UT_Electrical_Demand_Factor, UnitGroup.Electrical },
                { UnitType.UT_HVAC_DuctInsulationThickness, UnitGroup.HVAC },
                { UnitType.UT_HVAC_DuctLiningThickness, UnitGroup.HVAC },
                { UnitType.UT_PipeInsulationThickness, UnitGroup.Piping },
                { UnitType.UT_HVAC_ThermalResistance, UnitGroup.Energy },
                { UnitType.UT_HVAC_ThermalMass, UnitGroup.Energy },
                { UnitType.UT_Acceleration, UnitGroup.Structural },
                { UnitType.UT_Bar_Diameter, UnitGroup.Structural },
                { UnitType.UT_Crack_Width, UnitGroup.Structural },
                { UnitType.UT_Displacement_Deflection, UnitGroup.Structural },
                { UnitType.UT_Energy, UnitGroup.Structural },
                { UnitType.UT_Structural_Frequency, UnitGroup.Structural },
                { UnitType.UT_Mass, UnitGroup.Structural },
                { UnitType.UT_Mass_per_Unit_Length, UnitGroup.Structural },
                { UnitType.UT_Moment_of_Inertia, UnitGroup.Structural },
                { UnitType.UT_Surface_Area, UnitGroup.Structural },
                { UnitType.UT_Period, UnitGroup.Structural },
                { UnitType.UT_Pulsation, UnitGroup.Structural },
                { UnitType.UT_Reinforcement_Area, UnitGroup.Structural },
                { UnitType.UT_Reinforcement_Area_per_Unit_Length, UnitGroup.Structural },
                { UnitType.UT_Reinforcement_Cover, UnitGroup.Structural },
                { UnitType.UT_Reinforcement_Spacing, UnitGroup.Structural },
                { UnitType.UT_Rotation, UnitGroup.Structural },
                { UnitType.UT_Section_Area, UnitGroup.Structural },
                { UnitType.UT_Section_Dimension, UnitGroup.Structural },
                { UnitType.UT_Section_Modulus, UnitGroup.Structural },
                { UnitType.UT_Section_Property, UnitGroup.Structural },
                { UnitType.UT_Structural_Velocity, UnitGroup.Structural },
                { UnitType.UT_Warping_Constant, UnitGroup.Structural },
                { UnitType.UT_Weight, UnitGroup.Structural },
                { UnitType.UT_Weight_per_Unit_Length, UnitGroup.Structural },
                { UnitType.UT_HVAC_ThermalConductivity, UnitGroup.Energy },
                { UnitType.UT_HVAC_SpecificHeat, UnitGroup.Energy },
                { UnitType.UT_HVAC_SpecificHeatOfVaporization, UnitGroup.Energy },
                { UnitType.UT_HVAC_Permeability, UnitGroup.Energy },
                { UnitType.UT_Electrical_Resistivity, UnitGroup.Electrical },
                { UnitType.UT_MassDensity, UnitGroup.Common },
                { UnitType.UT_MassPerUnitArea, UnitGroup.Structural },
                { UnitType.UT_Pipe_Dimension, UnitGroup.Piping },
                { UnitType.UT_PipeMass, UnitGroup.Piping },
                { UnitType.UT_PipeMassPerUnitLength, UnitGroup.Piping },
                { UnitType.UT_HVAC_TemperatureDifference, UnitGroup.HVAC },
                { UnitType.UT_Piping_TemperatureDifference, UnitGroup.Piping },
                { UnitType.UT_Electrical_TemperatureDifference, UnitGroup.Electrical },
            };
        }

        /// <summary>
        /// Tries the get catalog string.
        /// </summary>
        /// <param name="unitType">Type of the unit.</param>
        /// <param name="catalogString">The catalog string.</param>
        /// <returns></returns>
        public static bool TryGetCatalogString(this UnitType unitType, out string catalogString)
        {
            return _utToCatalog.TryGetValue(unitType, out catalogString);
        }

        /// <summary>
        /// Tries the get group.
        /// </summary>
        /// <param name="unitType">Type of the unit.</param>
        /// <param name="group">The group.</param>
        /// <returns></returns>
        public static bool TryGetGroup(this UnitType unitType, out UnitGroup group)
        {
            return _utGroups.TryGetValue(unitType, out group);
        }

        public static bool TryGetUnitType(this string unitString, out UnitType unitType)
        {
            unitType = _utToCatalog?.Where(u => u.Value.Equals(unitString))?.Select(x => x.Key)?.FirstOrDefault() ?? UnitType.UT_Undefined;
            return !unitType.Equals(UnitType.UT_Undefined);
        }
    }
}
